# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/vishalakshi',
                'doc_host': 'https://vedicreader.github.io',
                'git_url': 'https://github.com/vedicreader/vishalakshi',
                'lib_path': 'vishalakshi'},
  'syms': {'vishalakshi.core': {'vishalakshi.core.foo': ('core.html#foo', 'vishalakshi/core.py')}}}
