"""pull the web, papers, video, files, code and JSON APIs into the vault, once or on a schedule

Docs: https://vedicreader.github.io/vishalakshi/acquire.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_acquire.ipynb.

# %% auto #0
__all__ = ['KIND_OF', 'ACTIONS', 'IMG_EXTS', 'clip', 'records_md', 'exif_meta', 'image_md', 'secs']

# %% ../nbs/01_acquire.ipynb #a547a620d100
import hashlib, json, re, time, uuid, warnings
from urllib.parse import urlparse
from fastcore.all import AttrDict, L, Path, chunked, first, patch
from fossick import json_records, md_title, read, what_is
from litesearch import code_exts, dir2files, pdf_parse, DOC_EXTS
from .core import Vault, KINDS, is_sanskrit_file
from pobblebonk import Pob, secs
from .jobs import Queue, Retry
import honker

_all_ = ['secs']   # pobblebonk's, which also understands 'M' and 'y'

# %% ../nbs/01_acquire.ipynb #c4c6b708b341
def clip(s:str, n:int=120) -> str:
    'Collapse whitespace and clip a scraped title to something a breadcrumb can carry.'
    return re.sub(r'\s+', ' ', (s or '').strip())[:n] or 'untitled'

#: A `fossick.read` kind, and what the vault files it as. A GitHub file is web: the URL is
#: its provenance, not the checkout.
KIND_OF = dict(web='web', arxiv='arxiv', youtube='youtube', ghfile='web', pdf='pdf', file='file')

# %% ../nbs/01_acquire.ipynb #10d37b588c17
@patch
def _file(self:Vault,
          r,                  # what `fossick.read` returned
          kind:str=None,      # override the kind it named
          title:str=None,     # override the title it found
          meta:dict=None,     # merged over the reader's own provenance
          force:bool=False,   # re-ingest a source already present
          **kw                # forwarded to `add`
) -> dict:
    'File a `fossick.read` result. The one place a fetched thing becomes a document.'
    if not r.ok: return dict(source=r.source, skipped=r.skipped, title=r.title or None)
    return dict(self.add(r.text, title or clip(r.title), source=r.source,
                         kind=kind or KIND_OF.get(r.kind, 'web'),
                         meta=dict(meta or {}, url=r.source, **r.meta), force=force, **kw),
                url=r.source)

@patch
def url(self:Vault,
        url:str,            # page to read
        title:str=None,     # defaults to the page's first heading, else its path
        sel:str=None,       # CSS selector to narrow the page before conversion
        kind:str='web',
        auto:bool=True,     # escalate plain -> heavy -> stealthy -> logged-in Chrome past bot walls
        meta:dict=None,
        force:bool=False,
        **kw                # forwarded to fossick.fetch (verify=, headers=, heavy=…)
) -> dict:
    'Fetch one URL, convert it to markdown and file it in the vault.'
    return self._file(read(url, sel=sel, auto=auto, **kw), kind=kind, title=title,
                      meta=meta, force=force)

@patch
def crawl(self:Vault, start_url:str, max_pages:int=10, sel:str=None, **kw) -> L:
    'Crawl a docs site or blog from a start URL and file every page in the vault.'
    from fossick import crawl as _crawl, to_md
    pgs = L((pg.url, to_md(pg, sel=sel)) for pg in _crawl(start_url, sel=sel, max_pages=max_pages, **kw))
    return L(self.add(md, md_title(md, u), source=u, kind='web',
                      meta=dict(url=u, via='crawl', root=start_url, fetched_at=time.time()))
             for u, md in pgs if md.strip())

@patch
def web(self:Vault,
        query:str,          # what to search for
        n:int=5,            # top results to read
        google:bool=False,  # real Google ranking via a stealth browser (slower)
        chars:int=60000,    # max markdown chars kept per source
        **kw                # forwarded to fossick.research
) -> AttrDict:
    'Search the web, read the top `n` results, and file all of them in the vault.'
    from fossick import research
    res = research(query, n=n, engine='google' if google else 'search', chars=chars, **kw)
    srcs = L(res['sources']).filter(lambda s: s['md'].strip() and s['href'])
    added = srcs.map(lambda s: dict(self.add(s['md'], clip(s['title']), source=s['href'], kind='web',
                                             meta=dict(url=s['href'], query=query, fetched_at=time.time())),
                                    url=s['href']))
    # dropped pages: bot walls vs empty results; only the former is worth retrying
    return AttrDict(query=query, n_found=len(res['sources']), added=added,
                    dropped=L(res.get('dropped') or []))

# %% ../nbs/01_acquire.ipynb #20617c45413f
@patch
def arxiv(self:Vault, id_or_url:str, save_dir:str=None, force:bool=False, **kw) -> dict:
    'Read an arXiv paper (metadata + full text) into the vault as `kind="arxiv"`.'
    if (v := self.route('arxiv')) is not self: return v.arxiv(id_or_url, save_dir=save_dir, force=force, **kw)
    return self._file(read(id_or_url, save_dir=save_dir or str(self.assets('pdfs')),
                           force=force, **kw), force=force)

@patch
def pdf(self:Vault, path_or_url:str, title:str=None, force:bool=False, **kw) -> dict:
    '''Read a PDF (local path or URL) into the vault, one tree node per heading.

    The page split is litesearch's `pdf_parse`, not `fossick.read(pages=True)`: the tree and its
    chunk sizes are measured against this extractor.'''
    from fossick import get_pdf
    if (p:=Path(path_or_url)).exists(): return self.add_file(p, title=title, kind='pdf', force=force)
    if (doc := get_pdf(path_or_url, **kw)) is None: return dict(source=path_or_url, skipped='not a PDF or could not be fetched')
    stem = path_or_url.rsplit('/', 1)[-1].split('?')[0]
    return self.add(list(enumerate(pdf_parse(doc, out_path=self.assets(stem or 'pdf')))),
                    title or clip(stem), source=path_or_url, kind='pdf', force=force,
                    meta=dict(url=path_or_url, fetched_at=time.time()))

@patch
def youtube(self:Vault, url:str, force:bool=False, **kw) -> dict:
    "Read a YouTube video's transcript and metadata into the vault."
    return self._file(read(url, force=force, **kw), force=force)

@patch
def github(self:Vault, url:str, **kw) -> AttrDict:
    'File a whole GitHub repo: prose to the vault, source to kosha, through `add_tree`.'
    return self.add_tree(read(url).meta['path'], **kw)

_GH_BLOB = re.compile(r'https?://github\.com/([^/]+)/([^/]+)/blob/[^/]+/(.+)')

@patch
def gh_file(self:Vault, url:str, title:str=None, **kw) -> dict:
    'File one file from GitHub: prose to the vault, source to kosha. The URL decides, before any fetch.'
    if not (m := _GH_BLOB.match(url)): return dict(source=url, skipped='not a GitHub file URL')
    owner, repo, path = m.groups()
    if Path(path).suffix.lower() in code_exts.split(','):
        from fossick import gh_clone
        d = gh_clone(f'https://github.com/{owner}/{repo}')
        return dict(source=url, kind='code', path=str(d/path), code=self.index_code(d))
    return self._file(read(url), title=title, **kw)

@patch
def grab(self:Vault,
         target:str,        # a URL, an arXiv id, a YouTube link, a GitHub repo or file, a PDF, a local file or a directory
         title:str=None,
         sel:str=None,      # CSS selector, for the web cases
         shelf:str=None,    # shelf to file it on; None -> whichever `KIND_SHELF` names for its kind
         crawl:bool=False,  # follow links from a web target instead of reading the one page
         max_pages:int=10,  # pages to visit when crawling
         **kw               # forwarded to whichever method the target names
):
    '''File anything, by looking at what it is: the one call a CLI or an agent needs.

    `fossick.what_is` names the target. The kinds handled here are the ones that are not one
    document: a tree, a repo, a PDF the tree wants page by page, and a source file for kosha.'''
    kind = 'sanskrit' if is_sanskrit_file(target) else what_is(target)
    v = self.shelf(shelf) if shelf else self.route(kind)
    if crawl:                        return v.crawl(target, max_pages=max_pages, sel=sel, **kw)
    if kind == 'dir':                return v.add_tree(target, **kw)
    if kind in ('file', 'sanskrit'): return v.add_file(target, title=title, **kw)
    if kind == 'pdf':                return v.pdf(target, title=title, **kw)
    if kind == 'github':             return v.github(target, **kw)
    if kind == 'ghfile':             return v.gh_file(target, title=title, **kw)
    if kind == 'arxiv':              return v.arxiv(target, **kw)
    if kind == 'youtube':            return v.youtube(target, **kw)
    return v.url(target, title=title, sel=sel, **kw)

@patch
def code(self:Vault, dir:str, types:str=code_exts, **kw) -> L:
    "File a source tree into the vault as `kind='code'`, so code and prose answer one query."
    return self.add_dir(dir, types=types, kind='code', **kw)

# %% ../nbs/01_acquire.ipynb #b665a3656d4982e4
@patch
def add_tree(self:Vault,
             dir:str,                # tree to ingest
             types:str=DOC_EXTS,     # extensions filed into the vault as prose
             code:bool=True,         # index source files with kosha, when the tree has any
             kind:str=None,          # override the kind for the prose half
             connect:bool=False,     # rebuild the entity graph at the end; see below
             verbose:bool=False,
             queue:bool=False,       # enqueue the work instead of doing it; `poll` or `drain` runs it
             batch:int=50,           # files per job when queueing
             **kw                    # forwarded to add_file
) -> AttrDict:
    '''Ingest a whole tree, each half to the index that can actually answer questions about it.'''
    p = Path(dir)
    if not p.is_dir(): raise ValueError(f'not a directory: {dir}')
    if queue: return self.enqueue_tree(p, types=types, code=code, kind=kind, batch=batch,
                                       connect=connect, **kw)
    docs = self.add_dir(p, types=types, kind=kind, **kw)
    srcs = dir2files(p, types=code_exts) if code else L()
    out = AttrDict(dir=str(p), docs=docs, n_docs=len(docs), n_code=len(srcs), code=None)
    if srcs:
        try: out.code = self.index_code(p, verbose=verbose)
        except Exception as e:
            warnings.warn(f'could not index {len(srcs)} source files with kosha '
                          f'({type(e).__name__}: {str(e)[:120]}); filing them as prose instead, so '
                          f'they are at least searchable. Install kosha for symbol search.')
            out.code = dict(error=f'{type(e).__name__}: {str(e)[:200]}', filed_as_prose=len(srcs))
            out.docs = docs + srcs.map(self.add_file, kind='code', **kw)
    if connect and (out.n_docs or out.code): out.graph = self.connect()
    return out

# %% ../nbs/01_acquire.ipynb #b1c90cd77b58aa2a
def _batch_key(paths) -> str:
    'A stable name for a batch of paths, so enqueueing the same batch twice while it is pending is a no-op.'
    return hashlib.sha256('\n'.join(sorted(paths)).encode()).hexdigest()[:16]

@patch
def enqueue_files(self:Vault,
                  files,            # paths to ingest
                  kind:str=None,    # override the kind inferred from the extension
                  batch:int=50,     # files per job; one job is one `add_files` call
                  route:bool=True,  # send Sanskrit sources to the Sanskrit shelf
                  priority:int=0,
                  **kw              # forwarded to add_files
) -> L:
    'Enqueue an ingest as one job per `batch` files, so a crash resumes at the last batch.'
    fs = L(files).map(Path)
    if not fs: return L()
    if route and self.name == 'store':
        sa, rest = L(), L()
        for f in fs: (sa if is_sanskrit_file(f) else rest).append(f)
        groups = [('sanskrit', sa), (self.name, rest)]
    else: groups = [(self.name, fs)]
    out = L()
    for store, g in groups:
        for ch in chunked(g, batch):
            ps = [str(p) for p in ch]
            out.append(self.q.enqueue('ingest', dict(store=store, kind=kind, files=ps, kw=kw),
                                      priority=priority, key=f'ingest:{store}:{_batch_key(ps)}'))
    return out

@patch
def enqueue_tree(self:Vault, dir, types:str=DOC_EXTS, code:bool=True, kind:str=None,
                 batch:int=50, connect:bool=False, **kw) -> AttrDict:
    'Enqueue a whole tree: one job per batch of documents, one more for the code half.'
    p, out = Path(dir), L()
    docs = dir2files(p, types=types)
    out += self.enqueue_files(docs, kind=kind, batch=batch, **kw)
    srcs = dir2files(p, types=code_exts) if code else L()
    if srcs: out.append(self.q.enqueue('index_code', dict(dir=str(p)), key=f'index_code:{p}'))
    # priority 1 sorts it behind the batches, and the handler waits for the ones it did not outrank.
    # the key has no tree in it because the graph is of the whole vault: one pending job covers every
    if connect and out: out.append(self.q.enqueue('connect', {}, priority=1, key='connect',
                                                  max_attempts=8))
    return AttrDict(dir=str(p), n_docs=len(docs), n_code=len(srcs), queued=len(out),
                    jobs=list(out.attrgot('id')))

@patch
def _job_ingest(self:Vault, payload:dict) -> dict:
    'Queue handler for one batch of files.'
    v = self if payload['store'] == self.name else self.shelf(payload['store'])
    fs = L(payload['files']).map(Path).filter(lambda p: p.exists())
    if not fs: return dict(skipped='every file in the batch is gone')
    docs = v.add_files(fs, kind=payload.get('kind'), **(payload.get('kw') or {}))
    return dict(store=payload['store'], files=len(fs), added=len(docs))

@patch
def _job_index_code(self:Vault, payload:dict) -> dict:
    "Queue handler for the kosha half of a tree. A kosha failure dead-letters rather than filing source as prose."
    return dict(dir=payload['dir'], code=self.index_code(payload['dir']))

@patch
def _job_connect(self:Vault, payload:dict) -> dict:
    'Queue handler rebuilding the entity graph, once the ingests it should cover have landed.'
    # the graph is of the whole vault, so any pending ingest is one this should wait for
    if (n := self.q.pending('ingest')): raise Retry(f'{n} ingest jobs still to run')
    return dict(graph=self.connect())

# %% ../nbs/01_acquire.ipynb #65225e9d6c6ca206
def records_md(recs, title_keys=('name', 'title', 'displayName', 'productName', 'label', 'sku', 'id')) -> str:
    'Records as markdown, one `##` section per record, so each becomes its own retrievable node.'
    def ttl(r): return clip(next((r[k] for k in title_keys if isinstance(r.get(k), str) and r[k].strip()),
                                 json.dumps(r, default=str)), 80)
    return '\n\n'.join(f'## {ttl(r)}\n\n```json\n{json.dumps(r, indent=1, default=str)}\n```'
                       for r in L(recs).map(lambda r: r if isinstance(r, dict) else dict(value=r)))

# %% ../nbs/01_acquire.ipynb #e47f869baa617740
@patch
def apis(self:Vault,
         url:str,             # page to watch
         pattern:str='*',     # glob/regex filtering captured request URLs
         session:bool=False,  # capture through the logged-in debug Chrome
         preview:int=240,     # chars of each response shown
         **kw                 # forwarded to fossick.find_xhr
) -> L:
    'Discover the JSON endpoints a page calls, so you can read its data instead of its HTML.'
    from fossick import find_xhr
    self._caps = L(find_xhr(url, pattern=pattern, session=session, **kw))
    return L(AttrDict(n=i, url=h['url'], content_type=h.get('content_type'),
                      records=len(json_records(h.get('data'))),
                      preview=json.dumps(h.get('data'), default=str)[:preview])
             for i, h in enumerate(self._caps))

@patch
def harvest(self:Vault,
            url:str,                # the page whose API you want
            pattern:str='*',        # which captured request URLs to keep
            title:str=None,         # document title; defaults to the page host + path
            capture:int=None,       # replay a specific endpoint from the last apis() call
            pages:int=1,            # pages to pull; >1 paginates the endpoint
            page_field:str='page',  # query/body key incremented per page
            session:bool=False,     # capture through the logged-in Chrome
            force:bool=False,
            **kw
) -> dict:
    "Sniff a page's JSON API, pull the records, and file them in the vault as `kind='data'`."
    from fossick import replay_xhr, paginate_api
    caps = getattr(self, '_caps', None)
    if capture is None or not caps:
        found = self.apis(url, pattern=pattern, session=session)
        if not found: return dict(url=url, skipped='no JSON endpoints captured')
        capture, caps = max(found, key=lambda h: h.records).n, self._caps
    cap, hit = caps[capture].get('capture'), caps[capture]
    ep = (cap or hit)['url']
    try:one, key = json_records(replay_xhr(cap, **kw).json() if cap else hit.get('data'), with_key=True)
    except Exception as e: return dict(url=url, endpoint=ep, skipped=f'{type(e).__name__}: {e}')
    if pages > 1 and one: kw.setdefault('page_size', len(one))
    items = (paginate_api(ep, payload=cap.get('request_body') if cap else None, page_field=page_field,
      results_field=key, method=(cap.get('method') or 'GET').upper() if cap else 'GET', max_pages=pages, **kw)
             if pages > 1 else one)
    if not items: return dict(url=url, endpoint=ep, skipped='no records found in the response')
    ttl = title or f'{urlparse(url).netloc}{urlparse(url).path}'.strip('/')
    return dict(self.add_records(items, ttl, source=ep, force=force, meta=dict(page=url, endpoint=ep,
           harvested_at=time.time())), endpoint=ep, records=len(items))

@patch
def add_records(self:Vault, recs:list, title:str, source:str=None, kind:str='data', force:bool=False,
                meta:dict=None) -> dict:
    'File a list of dicts you already have (any API, any export) as one document, one section each.'
    return self.add(f'# {title}\n\n{records_md(recs)}', title, source=source or f'records:{title}',
                    kind=kind, force=force, meta=dict(meta or {}, records=len(L(recs))))

# %% ../nbs/01_acquire.ipynb #30e68805575acb49
ACTIONS = ('url', 'web', 'harvest', 'arxiv', 'youtube', 'crawl', 'path', 'remind')

@patch(as_prop=True)
def q(self:Vault) -> Queue:
    "The vault's job queue, on its database, with the acquisition handlers registered."
    if (q := getattr(self.db, '_vq', None)) is None: q = self.db._vq = Queue(self.db)
    # a shelf may reach it first; the main store rebinds the handlers to itself when it arrives
    if self.name == 'store' or not q.handlers:
        for k, fn in (('watch', self._job_watch), ('ingest', self._job_ingest),
                      ('index_code', self._job_index_code), ('connect', self._job_connect)):
            q.register(k, fn)
    return q

@patch(as_prop=True)
def pob(self:Vault) -> Pob:
    "The vault's clock: pobblebonk's schedules, in the vault's own file. One schedule per watch."
    if (p := getattr(self.db, '_vp', None)) is None:
        # honker reads `PRAGMA data_version` off a file, so a `:memory:` vault gets a scratch one
        f = str(self.path)
        p = self.db._vp = Pob() if f in ('', ':memory:') else Pob(db=honker.open(f))
    # every watch runs the same callback, so a schedule read off disk still has one
    for r in p.all(): p.runners.setdefault(r['name'], self._fire_watch)
    return p

@patch
def _fire_watch(self:Vault, fire) -> dict:
    'What a due schedule does: put one `watch` job on the queue. Running it is still the queue.'
    return self.q.enqueue('watch', dict(watch_id=fire.schedule, scheduled_at=fire.fire_at),
                          key=f'{fire.schedule}@{int(fire.fire_at)}')

@patch
def _w(self:Vault):
    'The watches table, created on first use.'
    t = self.db.t.watches
    t.create(id=str, action=str, target=str, params=str, every=float, cron=str, note=str,
             enabled=int, last_run=float, last_status=str, runs=int, catchup=int, missed=int,
             pk='id', if_not_exists=True)
    have = set(t.columns_dict)
    for c, d in dict(catchup='INTEGER DEFAULT 1', missed='INTEGER DEFAULT 0', cron='TEXT').items():
        if c not in have: self.db.conn.execute(f'ALTER TABLE watches ADD COLUMN {c} {d}')
    return t

@patch
def watch(self:Vault,
          target:str,         # URL, query, arXiv id, or the text of a reminder
          action:str='url',   # one of ACTIONS: what to do when it fires
          every:str='1d',     # interval: '30m', '6h', '1d', '1w', '1M', or seconds
          cron:str=None,      # or a five-field cron expression, instead of an interval
          note:str=None,      # why you are watching
          start:float=None,   # first run time (epoch); defaults to the next boundary
          catchup:int=1,      # missed intervals to make up after a gap; the rest count as `missed`
          **params            # forwarded to the action (n=, pattern=, pages=, sel=, ...)
) -> dict:
    'Register a recurring job: re-read a page, re-run a search, re-harvest an API, or remind you.'
    assert action in ACTIONS, f'action must be one of {ACTIONS}'
    row = dict(id=uuid.uuid4().hex[:12], action=action, target=target, params=json.dumps(params),
               every=None if cron else secs(every), cron=cron, note=note or '', enabled=1, runs=0,
               catchup=max(1, int(catchup)), missed=0)
    self._w().insert(row, replace=True)
    p = self.pob
    p.runners[row['id']] = self._fire_watch
    # an interval watch is due at once, as it always was; a cron says for itself when it runs
    sched = p.add(row['id'], cron=cron, every=None if cron else row['every'],
                  catchup=row['catchup'],
                  start=start if start is not None else (None if cron else time.time()))
    return dict(row, params=params, next_run=sched.next_fire_at)

@patch
def watches(self:Vault, due_only:bool=False, at:float=None) -> L:
    'Every registered watch, soonest first; `due_only` keeps the ones whose next run has arrived.'
    nxt = {s['name']: s['next_fire_at'] for s in self.pob.all()}
    rows = L(self._w()(where='enabled=1' if due_only else None)).map(
        lambda r: dict(r, params=json.loads(r['params'] or '{}'), next_run=nxt.get(r['id'])))
    now = time.time() if at is None else at
    if due_only: rows = rows.filter(lambda r: r['next_run'] is not None and r['next_run'] <= now)
    return rows.sorted(key=lambda r: (r['next_run'] is None, r['next_run'] or 0))

@patch
def _watch_row(self:Vault, wid:str) -> dict|None:
    'One watch by id, with its params parsed.'
    r = first(self._w()(where='id=?', where_args=[wid]))
    return dict(r, params=json.loads(r['params'] or '{}')) if r else None

@patch
def unwatch(self:Vault, watch_id:str):
    'Delete a watch. The documents it already filed stay in the vault.'
    self.pob.drop(watch_id)
    self._w().delete(watch_id)

@patch
def pause(self:Vault, watch_id:str, enabled:bool=False):
    'Disable (or re-enable) a watch without losing it.'
    (self.pob.resume if enabled else self.pob.pause)(watch_id)
    self._w().update(dict(id=watch_id, enabled=int(enabled)))

@patch
def _do_watch(self:Vault, w:dict):
    'Perform one watch action. Raises on failure, and `Retry` where the failure is worth another try.'
    params = dict(w['params'])
    if w['action'] in ('url', 'arxiv', 'youtube', 'path'): params.setdefault('force', True)
    res = (self.note(w['target'], title=w.get('note') or None, tags=['reminder'])
           if w['action'] == 'remind' else self.grab(w['target'], **params)
           if w['action'] == 'path' else getattr(self, w['action'])(w['target'], **params))
    # a bot wall is a skip worth retrying; 'no transcript' is a skip that will never change
    if isinstance(res, dict) and res.get('skipped') and (res.get('status') or 0) >= 400:
        raise Retry(res['skipped'])
    return res

@patch
def _job_watch(self:Vault, payload:dict) -> dict:
    'Queue handler for a due watch: run it, and record the outcome on its row. `next_run` is the scheduler\'s.'
    if (w := self._watch_row(payload['watch_id'])) is None:
        return dict(skipped=f"watch {payload['watch_id']} is gone")
    def _done(st): self._w().update(dict(id=w['id'], last_run=time.time(), last_status=st, runs=w['runs']+1))
    try: res = self._do_watch(w)
    except Exception:
        _done('error'); raise
    _done('skipped' if isinstance(res, dict) and res.get('skipped') else 'ok')
    return res

@patch
def run_watch(self:Vault, w:dict) -> dict:
    'Fire one watch now, off the queue, and record the outcome. Failures come back, they do not raise.'
    t0 = time.time()
    try:
        res = self._job_watch(dict(watch_id=w['id']))
        status = 'skipped' if isinstance(res, dict) and res.get('skipped') else 'ok'
    except Exception as e: res, status = dict(error=f'{type(e).__name__}: {str(e)[:200]}'), 'error'
    # a due watch run by hand consumes its slot, or it stays due and the next poll runs it again
    p = self.pob
    if (s := p.get(w['id'])) is not None and s.next_fire_at <= t0: p.tick(at=t0, run=False)
    return dict(watch_id=w['id'], action=w['action'], target=w['target'], status=status,
                took=round(time.time()-t0, 2), result=res)

@patch
def schedule(self:Vault, at:float=None) -> L:
    'Enqueue a job for every watch that has come due. pobblebonk owns the clock and the catch-up.'
    t = self.pob.tick(at=at, run=True)
    for wid, n in (t.missed or {}).items():
        if (w := self._watch_row(wid)): self._w().update(dict(id=wid, missed=(w['missed'] or 0) + n))
    return L(r.result for r in t.ran if r.status == 'ok')

@patch
def poll(self:Vault, at:float=None, limit:int=None, connect:bool=True, worker:str='poll') -> dict:
    'Reclaim, schedule and drain. This is the tick a scheduler, a cron or a frontend calls.'
    back = self.q.reclaim()
    self.schedule(at=at)
    ran = self.q.drain(worker, limit=limit or 1000)
    if connect and ran.filter(lambda r: r['status'] == 'ok'): self.connect()
    pending = self.watches()
    return dict(checked=len(pending), ran=len(ran), results=list(ran), reclaimed=len(back),
                dead=self.q.stats()['dead'], next_due=pending[0]['next_run'] if pending else None)

@patch
def jobs(self:Vault, state:str=None, kind:str=None, limit:int=50) -> L:
    'Jobs in the vault queue; `state="dead"` is the ones that used up their attempts.'
    return self.q.jobs(state=state, kind=kind, limit=limit)

@patch
def retry_job(self:Vault, job_id:str) -> dict:
    'Put a dead or pending job back on the queue now, with its attempt count reset.'
    return self.q.retry(job_id)


# %% ../nbs/01_acquire.ipynb #cbf215018d3a0727
IMG_EXTS = set('.jpg .jpeg .png .gif .bmp .webp .tif .tiff .heic .heif .avif'.split())

_EXIF = {271: 'make', 272: 'model', 306: 'taken', 36867: 'taken', 33434: 'exposure',
         33437: 'f_number', 34855: 'iso', 37386: 'focal_length', 274: 'orientation'}

def exif_meta(path) -> dict:
    'Dimensions, camera, capture time and GPS for one image file.'
    from PIL import Image
    out = dict(filename=Path(path).name, folder=Path(path).parent.name, bytes=Path(path).stat().st_size)
    with Image.open(path) as im:
        out |= dict(width=im.width, height=im.height, format=im.format, mode=im.mode)
        try: ex = im.getexif()
        except Exception: ex = {}
        for k, n in _EXIF.items():
            if (v := ex.get(k)) not in (None, ''): out.setdefault(n, str(v).strip())
        if (gps := (ex.get_ifd(34853) if ex else None)): out |= _gps(gps)
    if (t := out.get('taken')): out['year'] = t[:4]
    return {k: v for k, v in out.items() if v not in (None, '')}

def _gps(g) -> dict:
    'Latitude and longitude in degrees from an EXIF GPS IFD.'
    def deg(v, ref):
        d = float(v[0]) + float(v[1])/60 + float(v[2])/3600
        return round(-d if str(ref).upper() in ('S', 'W') else d, 6)
    try: return dict(lat=deg(g[2], g.get(1, 'N')), lon=deg(g[4], g.get(3, 'E')))
    except Exception: return {}

# %% ../nbs/01_acquire.ipynb #8e7eb888c56ca35d
def image_md(meta:dict,          # what `exif_meta` found
             title:str,          # what to call it
             caption:str=None,   # a description, if anything wrote one
             labels=None         # what a classifier saw, most likely first
            ) -> str:
    'The searchable text for a picture: its own metadata, plus whatever a model or a person added.'
    lines = [f'# {title}', '']
    if caption: lines += [caption, '']
    if labels: lines += ['Labels: ' + ', '.join(str(l) for l in L(labels)), '']
    keys = 'filename folder width height format taken year make model lat lon iso f_number focal_length'.split()
    lines += [f'- {k}: {meta[k]}' for k in keys if k in meta]
    return '\n'.join(lines)

# %% ../nbs/01_acquire.ipynb #92ad6bce1bba9af2
@patch
def add_image(self:Vault,
              path:str,           # the picture
              title:str=None,     # defaults to the filename
              caption:str=None,   # a description, if you have one
              labels=None,        # what a classifier saw
              meta:dict=None,     # merged over what the file says about itself
              force:bool=False,
              **kw
             ) -> dict:
    'File one picture in the vault as `kind="image"`: its metadata is the text, the pixels stay on disk.'
    p = Path(path).expanduser()
    m = dict(exif_meta(p), path=str(p.resolve()), added_at=time.time(), **(meta or {}))
    if labels: m['labels'] = list(L(labels))
    if caption: m['caption'] = caption
    ttl = title or p.stem
    return self.add(image_md(m, ttl, caption, labels), ttl, source=str(p.resolve()), kind='image',
                    meta=m, force=force, **kw)

@patch
def add_images(self:Vault,
               dir:str,             # folder of pictures
               recurse:bool=True,
               labels:dict=None,    # {path: labels}, as `label_images` produces
               force:bool=False,
               **kw
              ) -> L:
    'File every picture under a directory, one document each.'
    d = Path(dir).expanduser()
    fs = L(d.rglob('*') if recurse else d.glob('*')).filter(lambda f: f.is_file() and f.suffix.lower() in IMG_EXTS)
    lab = {str(Path(k).resolve()): v for k, v in (labels or {}).items()}
    return L(fs.sorted()).map(lambda f: self.add_image(f, labels=lab.get(str(f.resolve())), force=force, **kw))

@patch
def images(self:Vault, limit:int=None) -> L:
    'Every picture in the vault, with the metadata it was filed with.'
    rows = self.sources(kind='image')
    return (rows[:limit] if limit else rows)

@patch
def tag_image(self:Vault, ref:str, labels=None, caption:str=None, **kv) -> dict:
    "Write what a model saw onto a picture already in the vault, and refresh its searchable text."
    d = self.doc(ref)
    m = self.set_meta(d['id'], **{k: v for k, v in dict(labels=list(L(labels)) if labels else None,
                                                            caption=caption).items() if v}, **kv)
    self.add(image_md(m, d['title'], m.get('caption'), m.get('labels')), d['title'],
             source=d['source'], kind='image', meta=m, force=True)
    return m

# %% ../nbs/01_acquire.ipynb #121dd4e169f900c5
@patch
def label_images(self:Vault,
                 dir:str,               # folder of pictures
                 model:str,             # an anya model: a path, a hub repo id, or an alias
                 topk:int=3,            # labels to keep per picture
                 min_score:float=0.0,   # ignore anything less confident
                 add:bool=True,         # file them in the vault as well as returning them
                 **kw                   # forwarded to anya.classify
                ) -> L:
    'Classify a folder with anya and file every picture in the vault with what the model saw.'
    try: from anya import classify
    except ImportError as e:
        raise ImportError('label_images needs anya: pip install anya') from e
    ps = classify(dir, model, topk=topk, **kw)
    labs = {p['src']: [d['label'] for d in p.get('preds', []) if d['score'] >= min_score]
            for p in ps.ok if p.get('src')}
    if add: self.add_images(dir, labels=labs, force=True)
    return L(AttrDict(src=k, labels=v) for k, v in labs.items())
