"""drive the vault from a terminal

Docs: https://vedicreader.github.io/vishalakshi/cli.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_cli.ipynb.

# %% auto #0
__all__ = ['CMDS', 'vault', 'cmd', 'jsonable', 'show', 'main']

# %% ../nbs/04_cli.ipynb #9c8e8aa7
import json, os, sys
from functools import cache, wraps
from inspect import Parameter, Signature, signature
from fastcore.all import L
from fastcore.script import anno_parser
from .core import Vault
from . import acquire, ask, code, extract   # noqa: F401 — these patch the Vault methods the CLI exposes

# %% ../nbs/04_cli.ipynb #11ed4c4a
CMDS = ('stats find sections context ask explain read related toc map sources doc document shelves '
        'elsewhere '
        'grab url web crawl arxiv pdf youtube add_file add_dir add_tree note code connect forget '
        'apis harvest add_records watch watches unwatch pause poll index_code code_search symbol '
        'where_to_add grep federate categorize categorize_all doctypes of_type ner extract '
        'extract_all ask_doc').split()

@cache
def vault(path:str=None) -> Vault:
    'The vault every command shares: `$VISHALAKSHI_VAULT`, else the default path.'
    return Vault(path or os.getenv('VISHALAKSHI_VAULT') or None,
                 offline=bool(os.getenv('VISHALAKSHI_OFFLINE')))

def cmd(name:str, vault_fn=vault):
    """A `Vault` method as a plain function: `self` and `**kw` dropped, docments kept.

    `__delwrap__` is what makes the second half work — `docments` walks it to find the comments in
    the original source, so `anno_parser` and MCP both get help text for free."""
    f = getattr(Vault, name)
    g = wraps(f)(lambda **kw: getattr(vault_fn(), name)(**kw))
    ps = [p for p in signature(f).parameters.values()
          if p.name != 'self' and p.kind is not Parameter.VAR_KEYWORD]
    g.__signature__, g.__delwrap__ = Signature(ps), f
    g.__annotations__ = {p.name: p.annotation for p in ps if p.annotation is not Parameter.empty}
    return g

# %% ../nbs/04_cli.ipynb #f0a650d6
def jsonable(o):
    "`json.dumps` fallback: `L` and friends become lists, numpy scalars numbers, the rest strings."
    if hasattr(o, '__iter__') and not isinstance(o, (str, bytes, dict)): return list(o)
    return o.item() if hasattr(o, 'item') else str(o)

def show(r):
    'Print a result: an answer as prose with its citations, anything else as JSON.'
    if isinstance(r, str): return print(r)
    if isinstance(r, dict) and 'answer' in r:
        print(r['answer'])
        # a code citation has no node_id: its handle is the path:line the hit came from
        for c in r.get('cited', []): print(f"  [{c['n']}] {c['breadcrumb']}  {c['node_id'] or c['source'] or ''}")
    else: print(json.dumps(r, indent=2, default=jsonable))

def main():
    'Entry point for the `vishalakshi` command. `vishalakshi <cmd> --help` documents any command.'
    name = sys.argv[1].replace('-', '_') if len(sys.argv) > 1 else None
    if name not in CMDS:
        print(f"Usage: vishalakshi <cmd> [args]\n\n  {'  '.join(CMDS)}\n", file=sys.stderr)
        sys.exit(0 if name is None else 1)
    del sys.argv[1]
    f = cmd(name)
    kw = anno_parser(f, prog=f'vishalakshi {name}').parse_args().__dict__
    show(f(**{k: v for k, v in kw.items() if k not in ('pdb', 'xtra')}))
