"""fill kosha from a repo, grep the working tree, and federate all of it with the prose

Docs: https://vedicreader.github.io/vishalakshi/code.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_code.ipynb.

# %% auto #0
__all__ = ['kosha_indexed', 'code_sections']

# %% ../nbs/03_code.ipynb #8262fd09
from fastcore.all import AttrDict, L, Path, patch
from litesearch import rrf_all
from .core import Vault, _gate


# %% ../nbs/03_code.ipynb #85effdc0
@patch
def kosha(self:Vault,
          dir:str=None,              # repo root; defaults to the cwd repo
          share_encoder:bool=False,  # embed code with the vault's encoder instead of kosha's
          **kw                       # forwarded to Kosha()
):
    'The `Kosha` for `dir`, cached on the vault so `index_code` and `code_search` hit one store.'
    from kosha import Kosha
    k, root = getattr(self, '_k', None), Path(dir).resolve() if dir else None
    if k is None or (root and k.root != root):
        # `Index` holds the encoder; kosha wants a callable that returns one
        if share_encoder and self.encoder: kw['efn'] = lambda: self.encoder
        self._k = k = Kosha(dir, **kw)
    return k

@patch
def index_code(self:Vault,
               dir:str=None,      # repo to index
               graph:bool=True,   # also build the AST call graph (callers, callees, PageRank)
               env:bool=False,    # also index installed packages (slow the first time)
               force:bool=False,  # reindex everything, graph included, rather than what changed
               verbose:bool=False,
               **kw               # forwarded to kosha's `sync`
) -> dict:
    "Point the vault at a repo and fill kosha's stores from it."
    k = self.kosha(dir)
    k.sync(dir=dir, repo=True, env=env, graph=graph, force=force, verbose=verbose, **kw)
    return k.status()

# %% ../nbs/03_code.ipynb #798d0458
@patch
def code_search(self:Vault, q:str, limit:int=10, dir:str=None, **kw) -> L:
    "Search code through kosha: FTS + ANN, fused and rank-boosted. Takes kosha's `key:value` filters."
    return self.kosha(dir).context(q, limit=limit, **kw)

@patch
def symbol(self:Vault, name:str, depth:int=1, dir:str=None) -> AttrDict:
    'A symbol in the call graph: its file, PageRank and degree, plus its callers and callees.'
    k = self.kosha(dir)
    return AttrDict(node=name, info=dict(k.ni(name) or {}), neighbors=L(k.neighbors(name, depth)))

@patch
def where_to_add(self:Vault, description:str, limit:int=5, dir:str=None) -> L:
    'Where in the indexed repo a described change belongs: kosha ranking over the call graph.'
    return self.kosha(dir).where_to_add(description, limit=limit)

@patch
def grep(self:Vault,
         pattern:str,       # a ripgrep regex
         dir:str='.',       # tree to search
         limit:int=20,      # matching lines returned
         **kw               # forwarded to rgapi.rg (glob=, ext=, context=, hidden=, ...)
) -> L:
    'Exact matches in the files on disk, through ripgrep. `.gitignore` applies.'
    from rgapi import rg
    return _rg(rg(pattern, root=dir, max_results=limit, smart_case=True, **kw))


# %% ../nbs/03_code.ipynb #c89161e3
def _prose(v, q, n, kind=None, source:str='prose') -> L:
    'Vault sections, normalised to the federated row shape. `source` names the shelf they came from.'
    return L(v.sections(q, limit=n, kind=kind)).map(
        lambda s: AttrDict(source=source, ref=s['node_id'], title=s['title'], where=s['breadcrumb'],
                           text=' '.join(s['snippets'])[:600], open=f"read({s['node_id']!r})"))

def _code(rows, leg:str) -> L:
    'kosha hits, normalised to the federated row shape.'
    def row(r):
        m = dict(r.get('metadata') or {})
        mod, path, ln = m.get('mod_name', ''), m.get('path', ''), m.get('lineno')
        return AttrDict(source=leg, ref=mod or path, title=mod or (Path(path).name if path else ''),
                        where=f'{path}:{ln}' if path and ln else (path or mod),
                        text=(r.get('content') or '')[:600],
                        open=f'symbol({mod!r})' if mod else f'open {path}')
    return L(rows).map(row)

def _rg(matches) -> L:
    'ripgrep lines, normalised to the federated row shape.'
    return L(matches).map(lambda m: AttrDict(source='grep', ref=f'{m.path}:{m.line_number}',
                                             title=Path(m.path).name, where=f'{m.path}:{m.line_number}',
                                             text=m.line.strip()[:600], open=f'open {m.path}'))

@patch
def federate(self:Vault,
             q:str,             # the query
             limit:int=12,      # fused hits returned
             prose:bool=True,   # the vault's own documents, papers, notes
             repo:bool=True,    # kosha's repo index
             env:bool=False,    # kosha's installed-package index
             grep:bool=True,    # ripgrep over the working tree
             kind:str=None,     # restrict the prose leg to some KINDS
             shelves=True,      # other shelves as their own legs: True for all, a list to pick, None for none
             weights:dict=None, # per-leg RRF weights, e.g. {'prose':1.0,'repo':1.5}
             dir:str=None,      # repo for the code and grep legs
             per_leg:int=None,  # hits pulled from each leg before fusion
             pii:str='off',     # off | redact | refuse, applied to every fused hit
             pii_ner:bool=False,# gate on titled names too
) -> AttrDict:
    'One ranked answer across prose, indexed code and the files on disk, fused by RRF.'
    n, legs = per_leg or max(limit, 10), {}
    def leg(nm, f):
        try: legs[nm] = f()
        except Exception as e: legs[f'{nm}_error'] = f'{type(e).__name__}: {str(e)[:120]}'
    if prose: leg('prose', lambda: _prose(self, q, n, kind=kind))
    names = (self.shelves().filter(lambda s: s['store'] != self.name and s['docs']).attrgot('store')
             if shelves is True else L(shelves))
    for sh in names:
        s = sh if isinstance(sh, Vault) else self.shelf(sh)
        leg(nm := f'shelf:{s.name}', lambda s=s, nm=nm: _prose(s, q, n, kind=kind, source=nm))
    if repo:  leg('repo', lambda: _code(self.kosha(dir).repo_context(q, limit=n), 'repo'))
    if env:   leg('env', lambda: _code(self.kosha(dir).env_context(q, limit=n), 'env'))
    if grep:  leg('grep', lambda: self.grep(q, dir or '.', limit=n))
    lists = {nm: rows for nm, rows in legs.items() if isinstance(rows, L) and rows}
    for nm, rows in lists.items():
        for i, r in enumerate(rows): r['_fid'] = f'{nm}:{r.ref or i}'
    fused = rrf_all(list(lists.values()), limit=limit, id_key='_fid',
                    weights=[(weights or {}).get(nm, 1.0) for nm in lists])
    out = AttrDict(query=q, hits=L(fused).map(AttrDict),
                   legs={nm: (len(r) if isinstance(r, L) else r) for nm, r in legs.items()},
                   note=f"RRF over {', '.join(lists) or 'nothing'}; the legs use different "
                        f"encoders, so ranks are fused, not distances")
    # the code legs are files, not sections, so a mark cannot reach them; the text is scanned instead
    return _gate(self, out, pii, pii_ner)

# %% ../nbs/03_code.ipynb #9e4d1a76
def kosha_indexed(dir:str=None) -> bool:
    'Has kosha already indexed this repo? A file check, so asking costs nothing.'
    from litesearch import repo_root
    d = Path(dir) if dir else repo_root()
    return bool(d) and (Path(d)/'.kosha'/'code.db').exists()

def code_sections(v,                 # the Vault
                  q:str,             # the question
                  n:int=4,           # code hits to keep
                  dir:str=None,      # repo for the kosha and ripgrep legs
                  **kw               # forwarded to federate
) -> L:
    'Federated code hits, shaped like vault sections so the rest of `ask` cannot tell the difference.'
    if not getattr(v, 'federate', None): return L()
    f = v.federate(q, limit=n, prose=False, dir=dir, **kw)
    return L(f.hits).map(lambda h: AttrDict(
        node_id=None, doc_id=None, title=h.get('title') or h.get('ref'), pages=None,
        breadcrumb=f"{h.get('source','code')} › {h.get('where') or h.get('ref')}",
        filename=h.get('where') or h.get('ref'), text=h.get('text') or '', via=h.get('source')))
