"""what a document is, the fields inside it, and an answer over the whole of it

Docs: https://vedicreader.github.io/vishalakshi/extract.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_extract.ipynb.

# %% auto #0
__all__ = ['DOCTYPE_SHELF', 'model_cached', 'DOCTYPES', 'EXTRACT_SP', 'FIELD_TYPES', 'KIND_BONUS', 'KIND_HINT', 'MIN_MARGIN',
           'MIN_SCORE', 'NER_CHARS', 'SCHEMAS', 'SIGNALS', 'TYPE_SP', 'Catalogue', 'Contract', 'Invoice',
           'MeetingNotes', 'Paper', 'Receipt', 'Resume', 'Summary', 'as_schema', 'cue_scores', 'dyn_schema',
           'guess_type', 'schema_str', 'signals', 'structured']

# %% ../nbs/06_extract.ipynb #a4b60d92
from collections import Counter
from fastcore.all import AttrDict, L, patch
from rahasya import NER_CHARS, pii_report, redact, redact_obj
from varga import (DOCTYPES, KIND_BONUS, KIND_HINT, MIN_MARGIN, MIN_SCORE, SIGNALS, TYPE_SP,
                   cue_scores, guess_type, signals)
from varga.schema import (EXTRACT_SP, FIELD_TYPES, SCHEMAS, Catalogue, Contract, Invoice,
                          MeetingNotes, Paper, Receipt, Resume, Summary, as_schema, dyn_schema,
                          schema_str, structured)
from .core import Vault
from .ask import (LOCAL_RUNTIMES, PII_SP, dflt_model, is_stock_chat,
                            new_chat, pii_model_, rishi)   # also patches Vault.ask

# re-exported: what varga decides is still reachable from the vault that stores the verdict
_all_ = ['DOCTYPES', 'EXTRACT_SP', 'FIELD_TYPES', 'KIND_BONUS', 'KIND_HINT', 'MIN_MARGIN',
         'MIN_SCORE', 'NER_CHARS', 'SCHEMAS', 'SIGNALS',
         'TYPE_SP', 'Catalogue', 'Contract', 'Invoice', 'MeetingNotes', 'Paper', 'Receipt',
         'Resume', 'Summary', 'as_schema', 'cue_scores', 'dyn_schema', 'guess_type', 'schema_str',
         'signals', 'structured']


# %% ../nbs/06_extract.ipynb #c93f1d68
def model_cached(mid:str) -> bool:
    'Is this model already in the Hugging Face cache? A cache scan, never a download.'
    try:
        from huggingface_hub import scan_cache_dir
        return any(r.repo_id == mid for r in scan_cache_dir().repos)
    except Exception: return False

@patch
def categorize(self:Vault,
               ref,                # doc_id, source, title, a path on disk, or a loaded `document()`
               model:str=None,     # an id, a path, `mlx/…`; None -> $VISHALAKSHI_MODEL
               chat_kw:dict=None,  # anything else rishi's `Chat` takes: temp, runtime, think, …
               llm:str='auto',     # 'auto' -> only when the cues cannot decide | 'always' | 'never'
               labels:str=None,    # comma-separated labels to choose from; None -> DOCTYPES
               max_chars:int=6000, # chars of the document the model and the cues see
               ner:bool=True,      # run entity extraction alongside the regex signals
               save:bool=True,     # write the verdict into the document's meta
) -> AttrDict:
    'What kind of document this is: invoice, catalogue, contract, paper, transcript, code…'
    d = (ref if isinstance(ref, dict) and 'text' in ref
         else self.document(ref, max_chars=max(max_chars, 4000)))
    txt = (d.text or '')[:max_chars]
    if not txt.strip():
        return AttrDict(doc_id=d.doc_id, title=d.title, doctype=None, skipped='no text to judge')
    sig = signals(txt, ner=ner)
    g = guess_type(txt, sig, kind=d.kind)
    dt, by = g.doctype, f'cues ({g.method})'
    mode = {True: 'always', False: 'never', None: 'auto'}.get(llm, str(llm).lower())
    assert mode in ('auto', 'always', 'never'), f"llm must be auto, always or never, not {llm!r}"
    if mode == 'always' or (mode == 'auto' and not g.decisive):
        lbls = L(labels.split(',') if isinstance(labels, str) else labels or list(DOCTYPES)).map(str.strip)
        mid = model or dflt_model
        try:
            # auto may use a model already loaded; it must not download one
            if mode == 'auto' and is_stock_chat() and rishi().infer_runtime(mid) != 'remote' and not model_cached(mid):
                by = f'cues ({g.method}); {mid or "no model"} is not downloaded, so none was asked'
            else:
                said = new_chat(mid, **(chat_kw or {})).classify(f'{d.title}\n\n{txt}', list(lbls)+['other'], sp=TYPE_SP)
                if said in lbls or said == 'other': dt, by = said, f'llm ({mid or "rishi default"})'
                else: by = f'cues ({g.method}); llm answered {said[:40]!r}, not a label'
        except Exception as e:
            # keep the cue verdict when the model leg fails
            if mode == 'always': raise
            by = f'cues ({g.method}); no model available ({type(e).__name__})'
    res = AttrDict(doc_id=d.doc_id, title=d.title, kind=d.kind, doctype=dt, score=g.score,
                   margin=g.margin, decisive=g.decisive, by=by, scores=g.scores,
                   signals=sig.counts, ents=sig.ents, saved=False)
    if save and d.doc_id:
        self.set_meta(d.doc_id, doctype=dt, doctype_by=by, doctype_score=g.score)
        res.saved = True
    return res

@patch
def categorize_all(self:Vault,
                   kind:str=None,     # restrict to one or more KINDS
                   force:bool=False,  # re-type documents that already carry a doctype
                   limit:int=None,    # stop after this many
                   **kw               # forwarded to categorize (model=, chat_kw=, llm=, ner=, max_chars=)
) -> AttrDict:
    'Type every document in the vault that is not typed yet, and report the shape of the corpus.'
    docs = self.sources(kind)
    if not force: docs = docs.filter(lambda r: not (r['meta'] or {}).get('doctype'))
    out = L()
    for r in docs[:limit]:
        try: out.append(self.categorize(r['id'], **kw))
        except Exception as e:
            out.append(AttrDict(doc_id=r['id'], title=r['title'], doctype=None,
                                error=f'{type(e).__name__}: {str(e)[:200]}'))
    return AttrDict(n=len(out), by_type=dict(Counter(o.doctype for o in out).most_common()),
                    errors=out.filter(lambda o: o.get('error')), results=out)

@patch
def doctypes(self:Vault, kind:str=None) -> dict:
    'How many documents of each type the vault holds. `untyped` counts the ones never categorised.'
    c = Counter((r['meta'] or {}).get('doctype') or 'untyped' for r in self.sources(kind))
    return dict(c.most_common())

@patch
def of_type(self:Vault, doctype:str, kind:str=None) -> L:
    'Every document categorised as `doctype`, newest first.'
    return self.sources(kind).filter(lambda r: (r['meta'] or {}).get('doctype') == doctype)

# doctype routing (KIND_SHELF is arrival kind)
DOCTYPE_SHELF = {'paper': 'papers', 'code': 'code', 'catalogue': 'data'}

@patch
def reshelf(self:Vault,
            ref,                      # doc_id, source, or a title substring
            shelf:str=None,           # where to put it; None -> whatever its doctype says
            llm:str='auto',           # the LLM leg of the categorisation that picks the shelf
            max_chars:int=2_000_000,  # cap on the text carried over
            **kw                      # forwarded to categorize (model=, chat_kw=, ner=)
) -> AttrDict:
    'Move a document to the shelf its *type* says it belongs on: the route that had to wait.'
    d = self.document(ref, max_chars=max_chars)
    c = self.categorize(d, save=False, llm=llm, **kw) if shelf is None else None
    nm = shelf or DOCTYPE_SHELF.get(c.doctype)
    out = AttrDict(doc_id=d.doc_id, title=d.title, doctype=c.doctype if c else None,
                   was=self.name, store=self.name, moved=False)
    if not nm or nm == self.name or not d.doc_id: return out
    r = self.shelf(nm).add(d.text, d.title, source=d.source, kind=d.kind, force=True,
                           meta=dict(d.meta, doctype=out.doctype, reshelved_from=self.name))
    self.forget(d.doc_id)
    return AttrDict(out, doc_id=r.get('doc_id'), store=nm, moved=True, chunks=r.get('chunks'))

@patch
def ner(self:Vault,
        ref:str,              # doc_id, source, title substring, or a path on disk
        limit:int=40,         # entities returned
        max_chars:int=20000,
) -> AttrDict:
    'What one document names: organisations, people, places, products, and the terms around them.'
    d = self.document(ref, max_chars=max_chars)
    sig = signals(d.text, limit=limit)
    return AttrDict(doc_id=d.doc_id, title=d.title, method=sig.method, counts=sig.counts,
                    labels=sig.labels, ents=sig.ents)


# %% ../nbs/06_extract.ipynb #b6a25c19
@patch
def extract(self:Vault,
            ref:str,               # doc_id, source, title substring, or a path on disk
            schema=None,           # a SCHEMAS key, a dataclass, or a 'field:type, …' spec; None -> from the doctype
            model:str=None,        # an id, a path, `mlx/…`; None -> $VISHALAKSHI_MODEL
            chat_kw:dict=None,     # anything else rishi's `Chat` takes: temp, runtime, think, …
            max_chars:int=8000,    # chars of the document the model sees
            sp:str=EXTRACT_SP,     # system prompt for the extraction
            save:bool=False,       # write the fields into the document's meta
            llm:str='auto',        # the LLM leg of the categorisation, when picking the schema
            pii:str='local',       # local|redact|refuse|off; same contract as `ask`
            pii_model:str=None,    # local model when private; None -> $VISHALAKSHI_PII_MODEL
) -> AttrDict:
    "Pull structured fields out of one document: an invoice's totals, a catalogue's products."
    d = self.document(ref, max_chars=max_chars)
    if not (d.text or '').strip():
        return AttrDict(doc_id=d.doc_id, title=d.title, source=d.source, doctype=None, schema=None,
                        fields={}, skipped='no text to extract from')
    # marks win over arithmetic, so this is `self.pii` rather than a bare `pii_report`
    report = (self.pii(d.doc_id, max_chars=max_chars) if d.doc_id else pii_report(d.text)) if pii != 'off' else None
    private, text = bool(report and report.has_pii), d.text
    if private and pii == 'refuse':
        return AttrDict(doc_id=d.doc_id, title=d.title, source=d.source, doctype=None, schema=None,
                        fields={}, skipped='pii', refused=True, pii=report)
    if private and pii == 'redact': text = redact(d.text)
    dt, cat = None, None
    if schema is None:
        cat = self.categorize(d, model=model, chat_kw=chat_kw, llm=llm, save=save)
        dt = cat.doctype
        sch = SCHEMAS.get(dt, Summary)
    else: sch = as_schema(schema)
    prompt = (f'{d.title}\n(source: {d.source})\n\n{text}\n\n---\n\n'
              f'Pull the fields of `{sch.__name__}` out of the document above.')
    mid, sys_sp = model, sp
    if private and pii == 'local':
        mid, sys_sp = pii_model or pii_model_, PII_SP
    ch = new_chat(mid, **(chat_kw or {}))
    if private and pii == 'local' and str(getattr(ch, 'runtime', '') or '') not in LOCAL_RUNTIMES:
        return AttrDict(doc_id=d.doc_id, title=d.title, source=d.source, doctype=dt, schema=None,
                        fields={}, skipped='pii', refused=True, pii=report, runtime=ch.runtime)
    flds = structured(ch, prompt, sch, sp=sys_sp)
    # the same backstop `ask` applies to an answer: fields are short, so names are looked for
    if private and pii_report(str(flds), ner=True).has_pii: flds = redact_obj(flds, ner=True)
    if save and d.doc_id: self.set_meta(d.doc_id, extracted=flds, extracted_as=sch.__name__)
    return AttrDict(doc_id=d.doc_id, title=d.title, source=d.source, doctype=dt, schema=sch.__name__,
                    fields=flds, chars=len(d.text), truncated=d.truncated, model=mid or dflt_model,
                    runtime=ch.runtime, categorized=cat, usage=getattr(ch, 'use', None), pii=report)

@patch
def extract_all(self:Vault,
                doctype:str=None,   # only documents already categorised as this
                kind:str=None,      # only these KINDS
                schema=None,        # one shape for all of them; None -> each document's own doctype
                limit:int=None,     # stop after this many
                **kw                # forwarded to extract (model=, chat_kw=, max_chars=, save=, sp=)
) -> AttrDict:
    'Extract from many documents at once: a folder of invoices as one table.'
    docs = self.of_type(doctype, kind) if doctype else self.sources(kind)
    rows, errs = L(), L()
    for r in docs[:limit]:
        try:
            e = self.extract(r['id'], schema=schema, **kw)
            if e.get('skipped'): errs.append(dict(doc_id=r['id'], title=r['title'], error=e.skipped))
            else: rows.append(dict({'doc_id': e.doc_id, 'doc_title': e.title, 'schema': e.schema},
                                   **e.fields))
        except Exception as ex:
            errs.append(dict(doc_id=r['id'], title=r['title'], error=f'{type(ex).__name__}: {str(ex)[:200]}'))
    return AttrDict(n=len(rows), doctype=doctype, schema=schema, rows=rows, errors=errs)


# %% ../nbs/06_extract.ipynb #7c4b0e91
@patch
def ask_doc(self:Vault,
            ref:str,              # doc_id, source, title substring, or a path on disk
            question:str,         # what you want to know about it
            schema=None,          # answer as this shape instead of prose
            max_chars:int=8000,   # chars of the document the model sees
            related:int=3,        # sections from the *rest* of the vault to add as context
            **kw                  # forwarded to `ask` (model=, chat_kw=, sp=)
) -> AttrDict:
    'Answer a question about one whole document: `ask` with that document as section [1].'
    return self.ask(question, ref=ref, schema=schema, doc_chars=max_chars, related=related, **kw)
