"""what a document *is*, the fields inside it, and an answer over the whole of it

Docs: https://vedicreader.github.io/vishalakshi/extract.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_extract.ipynb.

# %% auto #0
__all__ = ['SIGNALS', 'NER_CHARS', 'DOCTYPES', 'KIND_HINT', 'MIN_SCORE', 'MIN_MARGIN', 'KIND_BONUS', 'TYPE_SP', 'DOCTYPE_SHELF',
           'SCHEMAS', 'FIELD_TYPES', 'EXTRACT_SP', 'signals', 'cue_scores', 'guess_type', 'model_cached', 'Invoice',
           'Receipt', 'Catalogue', 'Contract', 'Resume', 'Paper', 'MeetingNotes', 'Summary', 'dyn_schema', 'as_schema',
           'schema_str', 'structured']

# %% ../nbs/06_extract.ipynb #a4b60d92
import json, re, warnings
from collections import Counter
from dataclasses import dataclass, fields, is_dataclass, make_dataclass, asdict
from typing import get_origin
from fastcore.all import AttrDict, L, patch
from litesearch import text_entities
from rishi.core import Chat, extract_fence, infer_runtime, resp_text
from .core import Vault
from .ask import VAULT_SP, dflt_model, is_stock_chat, new_chat, split_reasoning   # also patches Vault.ask

# %% ../nbs/06_extract.ipynb #d8c31e56
SIGNALS = dict(
    # what a document *contains*, as cheaply as a regex can tell — the evidence a type is scored on
    money    = r'[$€£¥₹]\s?\d[\d,]*(?:\.\d+)?|\b\d[\d,]*\.\d{2}\s?(?:usd|eur|gbp|inr|jpy|cad|aud)\b'
               r'|\b(?:usd|eur|gbp|inr|jpy|cad|aud)\s?\d[\d,]*',
    date     = r'\b\d{4}-\d{2}-\d{2}\b|\b\d{1,2}[/.]\d{1,2}[/.]\d{2,4}\b'
               r'|\b\d{1,2} (?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]* \d{2,4}\b'
               r'|\b(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]* \d{1,2},? \d{4}\b',
    time     = r'\b\d{1,2}:\d{2}(?::\d{2})?\s?(?:am|pm)?\b',
    ref      = r'\b(?:invoice|inv|order|p\.?o|ref(?:erence)?|receipt|bill|account|sku|part|item)\s*'
               r'(?:no\.?|number|id)?\s*[:#]\s*[a-z0-9][a-z0-9\-/]{2,}\b',
    qty      = r'\b(?:qty|quantity|units?|pcs?|nos?)\b\s*[:.]?\s*\d+|\b\d+\s?(?:x|×)\s?\d',
    percent  = r'\b\d{1,3}(?:\.\d+)?\s?%',
    tax      = r'\b(?:vat|gst|hsn|sac|tin|ein|abn|sales tax|tax id|withholding)\b',
    email    = r'\b[\w.+-]+@[\w-]+\.[\w.]{2,}\b',
    url      = r'https?://\S+',
    citation = r'\[\d+\]|\bet al\.|\bdoi:|\barxiv:',
    code     = r'^\s*(?:def|class|function|const|let|var|import|from|package|#include)\s+\w',
    table    = r'^\s*\|.+\|\s*$',
    heading  = r'^#{1,6} \S',
    blank    = r'_{4,}|\[ ?\]',
)
_SIG = {k: re.compile(v, re.I|re.M) for k, v in SIGNALS.items()}
# entity extraction runs on the head of a document — that is where its type is decided
NER_CHARS = 20000

# handrolled entity extraction: ORG by legal suffix, PERSON by honorific, LAW by instrument type
_ORG_SUFF = re.compile(
    r'(?<![a-z,\.])([A-Z][A-Za-z0-9\'\-& ]{1,50}?)\s+'
    r'(?:Ltd\.?|Limited|Corp\.?|Corporation|Inc\.?|LLC|LLP|GmbH|AG|SA|NV|BV|Pty\.?|PLC'
    r'|Group\b|Holdings?\b|Associates?\b|Partners?\b|Ventures?\b'
    r'|University\b|College\b|Institute\b|Hospital\b|Foundation\b'
    r'|Bank\b|Fund\b|Trust\b|Council\b|Authority\b|Commission\b'
    r'|Ministry\b|Department\b|Agency\b|Bureau\b)\b'
)
_PERSON_HON = re.compile(
    r'\b(?:Mr\.?|Mrs\.?|Ms\.?|Miss|Dr\.?|Prof(?:essor)?\.?|Rev\.?|Sir|Dame|Lord|Lady)\s+'
    r'([A-Z][a-z]+(?:\s+[A-Z][a-z]+){0,2})\b'
)
_LAW_INST = re.compile(
    r'\b([A-Z][A-Za-z ]{2,50}?)\s+'
    r'(?:Act(?:\s+\d{4})?|Regulations?\b|Directive\b|Ordinance\b|Statute\b|Treaty\b|Convention\b|Amendment\b)'
)

def _noun_ents(text:str, limit:int=40) -> L:
    'ORG, PERSON and LAW entities via regex — 89% of spaCy recall, zero model weight.'
    seen, out = set(), L()
    def _add(t, label):
        n = re.sub(r'\s+', ' ', t.strip())[:60]
        k = n.lower()
        if n and k not in seen: seen.add(k); out.append((n, label))
    for m in _ORG_SUFF.finditer(text): _add(m.group(0).strip(), 'ORG')
    for m in _PERSON_HON.finditer(text): _add(m.group(1), 'PERSON')
    for m in _LAW_INST.finditer(text): _add(m.group(1).strip(), 'LAW')
    return out[:limit]

def signals(text:str,            # the document text
            ner:bool=True,       # run entity extraction (noun entities + keyphrases)
            limit:int=20,        # entities kept
) -> AttrDict:
    'Countable evidence in one document: `counts` per signal, plus the entities it names.'
    counts = {k: len(p.findall(text or '')) for k, p in _SIG.items()}
    noun = L(_noun_ents((text or '')[:NER_CHARS]) if ner else ()).map(
        lambda t: AttrDict(label=t[1], text=t[0]))
    kws  = L(text_entities((text or '')[:NER_CHARS]) if ner else ()).map(
        lambda t: AttrDict(label=(t[1] or 'KEYPHRASE').upper(), text=re.sub(r'\s+', ' ', t[0].strip())[:60])
    ).filter(lambda e: e.text and e.label not in {'ORG', 'PERSON', 'LAW', 'PRODUCT', 'GPE'})
    found = noun + kws
    labels = dict(Counter(e.label.lower() for e in found))
    # `labels` is counted over everything found and `limit` caps only what is *shown*, because
    # `cue_scores` reads the labels: a display cap that silently moved a score would be a
    if noun:
        counts = {k: counts.get(k, 0) + (labels.get(k, 0) if k not in counts else 0)
                  for k in (*counts, *(l for l in labels if l not in ('keyphrase', 'term')))}
    return AttrDict(counts={k: v for k, v in counts.items() if v}, labels=labels,
                    ents=found.sorted(key=lambda e: e.label in ('KEYPHRASE', 'TERM'))[:limit],
                    method=('ner+regex' if noun else 'keyphrase+regex' if kws else 'regex'))

# %% ../nbs/06_extract.ipynb #5c2e8b14
DOCTYPES = {
    # label: the cue phrases that are evidence for it, the regex signals it needs, and the
    # entity labels it expects
    'invoice': dict(needs=('money',), ents=('ORG',), cues=(
        r'\b(?:tax )?invoice\b', r'\b(?:amount|balance|total) due\b', r'\bbill(?:ed)? to\b|\bremit\b',
        r'\bpayment terms?\b|\bnet \d{1,3}\b', r'\bsub-?total\b', r'\b(?:vat|gst|sales tax)\b')),
    'receipt': dict(needs=('money',), ents=('ORG',), cues=(
        r'\breceipt\b', r'\bthank you for your (?:order|purchase|payment)\b',
        r'\bcard\b[^\n]{0,16}\bending\b|\bcash tendered\b|\bchange due\b',
        r'\btransaction (?:id|no)\b|\bauth(?:orisation|orization) code\b',
        r'\bpaid\b|\bpayment received\b', r'\bmerchant\b|\bstore #\s?\d+\b')),
    'purchase_order': dict(needs=('ref',), ents=('ORG',), cues=(
        r'\bpurchase order\b|\bp\.?o\.?\s*(?:no|number|#)', r'\bship(?:[ -]?to)?\b',
        r'\bdelivery date\b|\brequested delivery\b', r'\bvendor\b|\bsupplier\b',
        r'\brequisition\b', r'\bunit price\b')),
    'quote': dict(needs=('money',), ents=('ORG',), cues=(
        r'\bquotation\b|\bquote\s*(?:no|number|#)|\bestimate\b', r'\bvalid (?:until|for|through)\b',
        r'\bunit price\b', r'\bterms and conditions\b',
        r'\bwe are pleased to (?:quote|offer)\b|\bno obligation\b')),
    'catalogue': dict(needs=('money',), ents=(), cues=(
        r'\bcatalog(?:ue)?\b|\bprice list\b|\bproduct list\b',
        r'\bsku\b|\bmodel\s*(?:no|number)\b|\bpart\s*(?:no|number)\b',
        r'\b(?:in|out of) stock\b|\bavailability\b', r'\bper (?:unit|pack|case|kg|litre|liter)\b',
        r'\bspecifications?\b|\bdimensions\b', r'\badd to (?:cart|basket)\b')),
    'contract': dict(needs=(), ents=('ORG', 'LAW'), cues=(
        r'\bagreement\b|\bcontract\b', r'\bparties\b|\bby and between\b',
        r'\bhereby\b|\bwhereas\b|\bhereinafter\b', r'\bshall\b',
        r'\bgoverning law\b|\bjurisdiction\b|\btermination\b',
        r'\bconfidential(?:ity)?\b|\bindemnif|\bliability\b')),
    'resume': dict(needs=('email',), ents=('PERSON', 'ORG'), cues=(
        r'\b(?:curriculum vitae|resum[eé])\b',
        r'\bwork experience\b|\bemployment history\b|\bprofessional experience\b',
        r'\beducation\b', r'\bskills\b', r'\bcertification',
        r'\breferences available\b|linkedin\.com/in/')),
    'paper': dict(needs=('citation',), ents=('ORG', 'PERSON'), cues=(
        r'\babstract\b', r'\bintroduction\b', r'\brelated work\b|\bmethodology\b|\bexperiments?\b',
        r'\breferences\b|\bbibliography\b', r'\bwe (?:propose|present|show|evaluate)\b',
        r'\bdoi:|\barxiv:')),
    'report': dict(needs=(), ents=('ORG',), cues=(
        r'\bexecutive summary\b', r'\bfindings\b|\bconclusions?\b|\brecommendations?\b',
        r'\bq[1-4] \d{4}\b|\bfiscal year\b|\bfy\d{2}\b|\bquarter\b',
        r'\btable \d+\b|\bfigure \d+\b|\bappendix\b',
        r'\byear[- ]on[- ]year\b|\brevenue\b|\bmargin\b')),
    # --- what an organisation writes about its own work, as opposed to what arrives from
    # outside
    'proposal': dict(needs=(), ents=('ORG',), cues=(
        r'\bproposal\b|\brfp response\b|\brequest for proposal\b', r'\bproposed approach\b|\bour approach\b',
        r'\bscope of work\b|\bwork ?plan\b', r'\bdeliverables?\b', r'\bfees?\b|\binvestment\b',
        r'\bproject team\b|\bteam structure\b')),
    'presentation': dict(needs=(), ents=(), cues=(
        r'\bslide deck\b|\bthis (?:deck|presentation)\b|\bslide \d+\b',
        r'\bkey takeaways?\b|\bkey messages?\b', r'\bfor discussion\b|\bquestions? for discussion\b',
        r'\bexecutive update\b|\bsteering committee\b|\bboard update\b',
        r'\bappendix slides?\b|\bback-?up slides?\b',
        r'\bagenda for (?:today|this session)\b|\bwalk(?:ing)? through\b')),
    'requirements_spec': dict(needs=(), ents=(), cues=(
        r'\brequirements? specification\b|\bproduct requirements?\b', r'\bacceptance criteria\b',
        r'\bfunctional requirements?\b|\bnon[- ]functional requirements?\b', r'\buser stor(?:y|ies)\b',
        r'\brequirement id\b|\btraceability matrix\b', r'\bthe system shall\b|\bmust be able to\b')),
    'technical_design': dict(needs=(), ents=(), cues=(
        r'\bsolution design\b|\btechnical design\b|\bdesign document\b',
        r'\bdata architecture\b|\bsystem architecture\b|\barchitecture (?:diagram|overview)\b',
        r'\bdata flow\b|\bsequence diagram\b|\bcomponent (?:diagram|view)\b',
        r'\bapplication hosting\b|\bnon[- ]functional\b|\bscalability\b',
        r'\bintegration (?:points?|patterns?|layer)\b|\binterface (?:contract|spec)\b',
        r'\bsubnet\b|\bapi gateway\b|\bdeployment (?:topology|diagram)\b')),
    'regulatory_guidance': dict(needs=(), ents=('LAW', 'ORG'), cues=(
        r'\bregulation \(?(?:eu|ec)\b|\bmedical device regulation\b', r'\bcompetent authority\b',
        r'\bnotified bod(?:y|ies)\b|\bconformity assessment\b', r'\bauthori[sz]ed representative\b',
        r'\btechnical documentation\b|\btechnical file\b', r'\barticle \d+\b|\bannex [ivx]+\b')),
    'procedure': dict(needs=(), ents=('ORG',), cues=(
        r'\bstandard operating procedure\b|\bs\.?o\.?p\.?\b|\bwork instruction\b',
        r'\bprocess owner\b|\bresponsibilit(?:y|ies)\b', r'\bapproval workflow\b|\bapproval authority\b',
        r'\bescalation\b|\bexception handling\b', r'\brevision history\b|\bchange control\b',
        r'\bthis procedure (?:applies|describes|covers)\b|\bscope and purpose\b')),
    'qa_artifact': dict(needs=(), ents=(), cues=(
        r'\btest (?:case|plan|script|protocol)\b', r'\bexpected results?\b|\bactual results?\b',
        r'\bsteps to reproduce\b|\bdefects?\b|\bbug report\b',
        r'\bdeviation log\b|\bdiscrepanc(?:y|ies)\b',
        r'\btemplate fidelity\b|\bvalidation report\b|\bqa audit\b',
        r'\bpass/fail\b|\btest (?:results?|status|evidence)\b')),
    'roadmap': dict(needs=(), ents=('ORG',), cues=(
        r'\broadmap\b', r'\bmilestones?\b', r'\bphase [0-9a-z]+\b|\bnow[,/ ]+next[,/ ]+later\b',
        r'\bnext (?:30|60|90) days\b|\bquarterly plan\b', r'\btarget date\b|\bplanned date\b',
        r'\bproduct backlog\b|\bdelivery plan\b|\bthemes?\b')),
    # a claim and a clinical record were one label until the cues were written down: they
    # share a shape (a dated record about a person) and no vocabulary at all, and a document
    # that
    'claim': dict(needs=('date',), ents=('PERSON', 'ORG'), cues=(
        r'\bclaim (?:number|no\.?|form|reference)\b|\bclaim id\b',
        r'\bincident date\b|\bdate of loss\b', r'\bclaimant\b|\binsured\b|\bpolicyholder\b',
        r'\bpolicy (?:number|no\.?|#)\b|\bcoverage\b', r'\b(?:loss )?adjuster\b|\bassessor\b',
        r'\bsettlement\b|\bdeductible\b|\bexcess\b|\bliability accepted\b')),
    'clinical_record': dict(needs=('date',), ents=('PERSON', 'ORG'), cues=(
        r'\bpatient\b|\bencounter\b', r'\bdiagnos(?:is|es|ed)\b|\bicd-?10\b',
        r'\bpresenting complaint\b|\bclinical (?:history|notes?)\b',
        r'\bprescri(?:bed|ption)\b|\bmedication\b|\bdosage\b',
        r'\bdischarge summary\b|\breferral letter\b|\bclinician\b|\bphysician\b',
        r'\badverse events?\b|\bdevice malfunction\b|\bside effects?\b')),
    'documentation': dict(needs=('heading',), ents=(), cues=(
        r'\binstallation\b|\bgetting started\b|\bquick ?start\b',
        r'\busage\b|\bexamples?\b|\bapi reference\b', r'\bparameters?\b|\breturns\b|\barguments?\b',
        r'\bpip install\b|\bnpm install\b|\bdocker run\b', r'\bconfiguration\b|\bsee also\b',
        r'^```')),
    'code': dict(needs=('code',), ents=(), cues=(
        r'^\s*(?:def|class)\s+\w+|^\s*(?:function|const|let|var)\s+\w+',
        r'^\s*(?:import|from|#include|package|use)\s+\w', r'\breturn\b',
        r'^\s*(?://|#|/\*)', r'\b(?:if|for|while)\s*\(', r'\b(?:public|private|static|async)\b')),
    'email': dict(needs=('email',), ents=('PERSON',), cues=(
        r'^(?:from|to|cc|bcc|subject|sent):', r'^\s*(?:dear|hi|hello)\b',
        r'\b(?:best|kind) regards\b|\bsincerely\b|\bthanks,\b',
        r'\bforwarded message\b|\bwrote:\s*$', r'\bunsubscribe\b')),
    'meeting_notes': dict(needs=(), ents=('PERSON',), cues=(
        r'\b(?:meeting|call) notes\b|\bminutes\b', r'\battendees\b|\bparticipants\b|\bpresent\b',
        r'\bagenda\b', r'\baction items?\b|\bnext steps\b|\bfollow[- ]ups?\b',
        r'\bdecided\b|\bdecisions?\b|\bowner\b|\bdue by\b')),
    'form': dict(needs=('blank',), ents=(), cues=(
        r'\bplease (?:complete|fill|print|sign)\b', r'\bfor office use only\b',
        r'\bapplicant\b|\bapplication (?:form|for)\b', r'\bsignature\b|\bdate signed\b',
        r'\b(?:full name|surname|given names?|date of birth|dob)\b', r'_{4,}')),
    'transcript': dict(needs=('time',), ents=('PERSON',), cues=(
        r'\btranscript\b', r'^\s*\[?\d{1,2}:\d{2}', r'^\s*(?:speaker \d|[A-Z][a-z]+\s?[A-Z]?[a-z]*):',
        r'\b(?:um|uh|you know|i mean)\b', r'\bwelcome (?:back|to)\b|\bthanks for (?:watching|listening)\b')),
    'article': dict(needs=(), ents=('PERSON', 'ORG'), cues=(
        r'\bpublished\b|\bposted (?:on|by)\b', r'\bread more\b|\bshare this\b|\bcomments?\b',
        r'\bsubscribe\b|\bnewsletter\b', r'\baccording to\b', r'\btags?:|\bcategor(?:y|ies):')),
}
_CUES = {l: [re.compile(c, re.I|re.M) for c in d['cues']] for l, d in DOCTYPES.items()}

# What acquired a document is evidence about what it is, and better evidence than any cue
# phrase: a YouTube ingest *is* a transcript
KIND_HINT = dict(youtube='transcript', arxiv='paper', code='code')
MIN_SCORE, MIN_MARGIN, KIND_BONUS = 0.4, 0.12, 0.2

def cue_scores(text:str, sig=None) -> dict:
    'Every doctype scored against `text`, best first — the categorisation no model is needed for.'
    sig = sig if sig is not None else signals(text)
    ner, out = sig.method.startswith('ner'), {}
    for lbl, d in DOCTYPES.items():
        cues = [p for p in _CUES[lbl] if p.search(text or '')]
        need = [s for s in d['needs'] if sig.counts.get(s)]
        ents = [e for e in d['ents'] if sig.labels.get(e.lower())] if ner else []
        legs = [(0.6, len(cues)/len(_CUES[lbl]))]
        if d['needs']: legs.append((0.25, len(need)/len(d['needs'])))
        if ner and d['ents']: legs.append((0.15, len(ents)/len(d['ents'])))
        w = sum(x for x, _ in legs)
        out[lbl] = round(sum(x*f for x, f in legs)/w, 3)
    return dict(sorted(out.items(), key=lambda kv: -kv[1]))

def guess_type(text:str,             # the document text
               sig=None,             # a signals() result, computed if not given
               kind:str=None,        # the vault kind that acquired it, if known
               min_score:float=MIN_SCORE,    # below this the cues have not decided
               min_margin:float=MIN_MARGIN,  # runner-up this close means they have not either
) -> AttrDict:
    'The best doctype for `text` from cues alone, and whether that guess is worth trusting.'
    sig = sig if sig is not None else signals(text)
    sc = cue_scores(text, sig)
    if kind in KIND_HINT: sc[KIND_HINT[kind]] = round(min(1.0, sc[KIND_HINT[kind]] + KIND_BONUS), 3)
    ranked = sorted(sc.items(), key=lambda kv: -kv[1])
    (top, best), (_, second) = ranked[0], (ranked[1] if len(ranked) > 1 else ('', 0.0))
    return AttrDict(doctype=top if best else 'other', score=best, margin=round(best-second, 3),
                    decisive=best >= min_score and best-second >= min_margin,
                    scores=dict(ranked[:5]), method=sig.method)

# %% ../nbs/06_extract.ipynb #c93f1d68
TYPE_SP = """You label one document with what kind of thing it is.

Judge the document as a whole, by its purpose, not by a word that happens to appear in it: a paper
about invoicing is a paper. Reply with exactly one label from the list and nothing else."""

def model_cached(mid:str) -> bool:
    'Is this model already in the Hugging Face cache? A cache scan, never a download.'
    try:
        from huggingface_hub import scan_cache_dir
        return any(r.repo_id == mid for r in scan_cache_dir().repos)
    except Exception: return False

@patch
def categorize(self:Vault,
               ref,                # doc_id, source, title, a path on disk, or a loaded `document()`
               model:str=None,     # an id, a path, `mlx/…`; None -> $VISHALAKSHI_MODEL
               chat_kw:dict=None,  # anything else rishi's `Chat` takes: temp, runtime, think, …
               llm:str='auto',     # 'auto' -> only when the cues cannot decide | 'always' | 'never'
               labels:str=None,    # comma-separated labels to choose from; None -> DOCTYPES
               max_chars:int=6000, # chars of the document the model and the cues see
               ner:bool=True,      # run entity extraction alongside the regex signals
               save:bool=True,     # write the verdict into the document's meta
) -> AttrDict:
    'What kind of document this is: invoice, catalogue, contract, paper, transcript, code…'
    d = (ref if isinstance(ref, dict) and 'text' in ref
         else self.document(ref, max_chars=max(max_chars, 4000)))
    txt = (d.text or '')[:max_chars]
    if not txt.strip():
        return AttrDict(doc_id=d.doc_id, title=d.title, doctype=None, skipped='no text to judge')
    sig = signals(txt, ner=ner)
    g = guess_type(txt, sig, kind=d.kind)
    dt, by = g.doctype, f'cues ({g.method})'
    mode = {True: 'always', False: 'never', None: 'auto'}.get(llm, str(llm).lower())
    assert mode in ('auto', 'always', 'never'), f"llm must be auto, always or never — not {llm!r}"
    if mode == 'always' or (mode == 'auto' and not g.decisive):
        lbls = L(labels.split(',') if isinstance(labels, str) else labels or list(DOCTYPES)).map(str.strip)
        mid = model or dflt_model
        try:
            # `auto` is allowed to *use* a model, not to go and fetch one: a vault of ten
            # thousand documents must not turn a one-line note into a multi-gigabyte download
            if mode == 'auto' and is_stock_chat() and infer_runtime(mid) != 'remote' and not model_cached(mid):
                by = f'cues ({g.method}); {mid or "no model"} is not downloaded, so none was asked'
            else:
                said = new_chat(mid, **(chat_kw or {})).classify(f'{d.title}\n\n{txt}', list(lbls)+['other'], sp=TYPE_SP)
                if said in lbls or said == 'other': dt, by = said, f'llm ({mid or "rishi default"})'
                else: by = f'cues ({g.method}); llm answered {said[:40]!r}, not a label'
        except Exception as e:
            # There may be no weights and no network, and a corpus 90% typed by cues alone is
            # worth far more than a traceback — so the cue verdict stands, and says why
            if mode == 'always': raise
            by = f'cues ({g.method}); no model available ({type(e).__name__})'
    res = AttrDict(doc_id=d.doc_id, title=d.title, kind=d.kind, doctype=dt, score=g.score,
                   margin=g.margin, decisive=g.decisive, by=by, scores=g.scores,
                   signals=sig.counts, ents=sig.ents, saved=False)
    if save and d.doc_id:
        self.set_meta(d.doc_id, doctype=dt, doctype_by=by, doctype_score=g.score)
        res.saved = True
    return res

@patch
def categorize_all(self:Vault,
                   kind:str=None,     # restrict to one or more KINDS
                   force:bool=False,  # re-type documents that already carry a doctype
                   limit:int=None,    # stop after this many
                   **kw               # forwarded to categorize (model=, chat_kw=, llm=, ner=, max_chars=)
) -> AttrDict:
    'Type every document in the vault that is not typed yet, and report the shape of the corpus.'
    docs = self.sources(kind)
    if not force: docs = docs.filter(lambda r: not (r['meta'] or {}).get('doctype'))
    out = L()
    for r in docs[:limit]:
        try: out.append(self.categorize(r['id'], **kw))
        except Exception as e:
            out.append(AttrDict(doc_id=r['id'], title=r['title'], doctype=None,
                                error=f'{type(e).__name__}: {str(e)[:200]}'))
    return AttrDict(n=len(out), by_type=dict(Counter(o.doctype for o in out).most_common()),
                    errors=out.filter(lambda o: o.get('error')), results=out)

@patch
def doctypes(self:Vault, kind:str=None) -> dict:
    'How many documents of each type the vault holds — `untyped` counts the ones never categorised.'
    c = Counter((r['meta'] or {}).get('doctype') or 'untyped' for r in self.sources(kind))
    return dict(c.most_common())

@patch
def of_type(self:Vault, doctype:str, kind:str=None) -> L:
    'Every document categorised as `doctype`, newest first.'
    return self.sources(kind).filter(lambda r: (r['meta'] or {}).get('doctype') == doctype)

# What a document turned out to *be* — as opposed to how it arrived, which is what
# `KIND_SHELF` covers
DOCTYPE_SHELF = {'paper': 'papers', 'code': 'code', 'catalogue': 'data'}

@patch
def reshelf(self:Vault,
            ref,                      # doc_id, source, or a title substring
            shelf:str=None,           # where to put it; None -> whatever its doctype says
            llm:str='auto',           # the LLM leg of the categorisation that picks the shelf
            max_chars:int=2_000_000,  # cap on the text carried over
            **kw                      # forwarded to categorize (model=, chat_kw=, ner=)
) -> AttrDict:
    'Move a document to the shelf its *type* says it belongs on — the route that had to wait.'
    d = self.document(ref, max_chars=max_chars)
    c = self.categorize(d, save=False, llm=llm, **kw) if shelf is None else None
    nm = shelf or DOCTYPE_SHELF.get(c.doctype)
    out = AttrDict(doc_id=d.doc_id, title=d.title, doctype=c.doctype if c else None,
                   was=self.name, store=self.name, moved=False)
    if not nm or nm == self.name or not d.doc_id: return out
    r = self.shelf(nm).add(d.text, d.title, source=d.source, kind=d.kind, force=True,
                           meta=dict(d.meta, doctype=out.doctype, reshelved_from=self.name))
    self.forget(d.doc_id)
    return AttrDict(out, doc_id=r.get('doc_id'), store=nm, moved=True, chunks=r.get('chunks'))

@patch
def ner(self:Vault,
        ref:str,              # doc_id, source, title substring, or a path on disk
        limit:int=40,         # entities returned
        max_chars:int=20000,
) -> AttrDict:
    'What one document names: organisations, people, places, products — and the terms around them.'
    d = self.document(ref, max_chars=max_chars)
    sig = signals(d.text, limit=limit)
    return AttrDict(doc_id=d.doc_id, title=d.title, method=sig.method, counts=sig.counts,
                    labels=sig.labels, ents=sig.ents)

# %% ../nbs/06_extract.ipynb #8d1c6a35
@dataclass
class Invoice:
    """An invoice, purchase order or quotation.

    Amounts are bare numbers with the currency in `currency`; dates are ISO (2024-03-01).
    """
    number:str = ''
    date:str = ''
    due_date:str = ''
    vendor:str = ''
    vendor_tax_id:str = ''
    bill_to:str = ''
    ship_to:str = ''
    currency:str = ''
    subtotal:float = 0
    tax:float = 0
    total:float = 0
    payment_terms:str = ''
    items:list[dict] = None

@dataclass
class Receipt:
    """A receipt for a completed payment.

    items: one entry per line, each {description, qty, amount}. `paid_with` is the tender or the
    last digits of the card. Dates are ISO (2024-03-01)."""
    merchant:str = ''
    date:str = ''
    transaction_id:str = ''
    currency:str = ''
    subtotal:float = 0
    tax:float = 0
    total:float = 0
    paid_with:str = ''
    items:list[dict] = None

@dataclass
class Catalogue:
    """A product catalogue, price list or listing page.

    products: one entry per product, each {sku, name, category, price, currency, availability, url}.
    Prices are bare numbers."""
    name:str = ''
    vendor:str = ''
    currency:str = ''
    updated:str = ''
    n_products:int = 0
    products:list[dict] = None

@dataclass
class Contract:
    """An agreement between parties.

    parties: the legal names. obligations: what each side must do. Dates are ISO (2024-03-01)."""
    title:str = ''
    parties:list[str] = None
    effective_date:str = ''
    end_date:str = ''
    term:str = ''
    value:str = ''
    governing_law:str = ''
    termination:str = ''
    obligations:list[str] = None

@dataclass
class Resume:
    """One person's CV.

    experience: one entry per role, each {employer, title, start, end, summary}.
    education: one entry per qualification, each {institution, qualification, year}."""
    name:str = ''
    email:str = ''
    phone:str = ''
    location:str = ''
    headline:str = ''
    years_experience:float = 0
    skills:list[str] = None
    experience:list[dict] = None
    education:list[dict] = None

@dataclass
class Paper:
    """An academic paper. authors: names in order. findings: the claims the paper actually makes."""
    title:str = ''
    authors:list[str] = None
    venue:str = ''
    year:str = ''
    doi:str = ''
    abstract:str = ''
    method:str = ''
    findings:list[str] = None
    limitations:list[str] = None

@dataclass
class MeetingNotes:
    """Notes from one meeting. actions: one entry per commitment, each {what, owner, due}."""
    title:str = ''
    date:str = ''
    attendees:list[str] = None
    topics:list[str] = None
    decisions:list[str] = None
    actions:list[dict] = None

@dataclass
class Summary:
    """What one document says, when no more specific shape fits.

    entities: the organisations, people and places it names. dates: ISO where the document allows."""
    title:str = ''
    doctype:str = ''
    about:str = ''
    key_points:list[str] = None
    entities:list[str] = None
    dates:list[str] = None
    numbers:list[str] = None
    open_questions:list[str] = None

# A purchase order and a quotation carry an invoice's fields under other names, so they share
# its schema rather than getting a near-duplicate of it
SCHEMAS = dict(invoice=Invoice, purchase_order=Invoice, quote=Invoice, receipt=Receipt,
               catalogue=Catalogue, contract=Contract, resume=Resume, paper=Paper,
               meeting_notes=MeetingNotes, other=Summary)

FIELD_TYPES = {'str':str, 'text':str, 'int':int, 'float':float, 'number':float, 'num':float, 'bool':bool,
               'list':list, 'dict':dict, 'strs':list[str], 'dicts':list[dict],
               'list[str]':list[str], 'list[dict]':list[dict]}
_DFLT = {str: '', int: 0, float: 0.0, bool: False}

def dyn_schema(spec,                    # 'vendor:str, total:float, items:dicts', or {'vendor':'str'}, or ['vendor']
               name:str='Extracted',    # class name, which the model sees
               doc:str=None,            # class docstring, which the model also sees
) -> type:
    'A dataclass built at runtime from a field spec — the shape of an answer, named in one string.'
    if isinstance(spec, str): spec = [p for p in re.split(r'[,\n]', spec) if p.strip()]
    if isinstance(spec, dict): spec = [f'{k}:{v}' for k, v in spec.items()]
    flds = []
    for p in spec:
        nm, _, ty = (p if isinstance(p, str) else ':'.join(p)).partition(':')
        t = FIELD_TYPES.get(ty.strip().lower() or 'str', str)
        flds.append((re.sub(r'\W', '_', nm.strip()), t, _DFLT.get(t, None)))
    if not flds: raise ValueError(f'no fields in schema spec {spec!r}')
    return make_dataclass(re.sub(r'\W', '', name) or 'Extracted', flds,
                          namespace=dict(__doc__=doc or 'The fields to pull out of the document.'))

def as_schema(spec, name:str='Extracted', doc:str=None) -> type:
    'Whatever names a shape, as a dataclass: a `SCHEMAS` key, a dataclass, or a `dyn_schema` spec.'
    if is_dataclass(spec): return spec
    if isinstance(spec, str) and spec.strip() in SCHEMAS: return SCHEMAS[spec.strip()]
    return dyn_schema(spec, name=name, doc=doc)

def _norm(obj, schema) -> dict:
    "A structured reply as a plain dict, with the `None` a list field defaults to turned back into `[]`."
    d = asdict(obj) if is_dataclass(obj) and not isinstance(obj, type) else dict(obj or {})
    lists = {f.name for f in fields(schema) if f.type is list or get_origin(f.type) is list}
    return {k: ([] if v is None and k in lists else v) for k, v in d.items()}

def schema_str(schema) -> str:
    "A schema written out for a model to read: its docstring, then `name: type` per field."
    def ty(t):
        if isinstance(t, str): return t
        # `list[dict].__name__` is just 'list' — the parameter is the half the model needs
        return str(t).replace('typing.', '') if get_origin(t) else getattr(t, '__name__', str(t))
    return ((schema.__doc__ or '').strip() + '\n\n{\n'
            + ',\n'.join(f'  "{f.name}": {ty(f.type)}' for f in fields(schema)) + '\n}')

def _json_reply(ch, prompt:str, schema, sp:str='') -> object:
    'Ask for the shape as a JSON object in prose and rebuild it, with the model left unconstrained.'
    ch.hist = []
    txt = resp_text(ch(f'{sp}\n\n{prompt}\n\nReply with only a JSON object in a ```json fence, with '
                       f'exactly these keys and types:\n\n{schema_str(schema)}'))
    d = json.loads(extract_fence(split_reasoning(txt)[0], 'json'))
    nms = {f.name for f in fields(schema)}
    return schema(**{k: v for k, v in d.items() if k in nms})

def structured(ch,                # a `rishi.Chat`, e.g. from `new_chat`
               prompt:str,        # the document and the instruction
               schema,            # the dataclass the reply must fill
               sp:str='',         # system prompt for the extraction
) -> dict:
    'A structured reply as a dict — retried as a plain JSON reply when the constrained call fails.'
    try: return _norm(ch.structured(prompt, schema, sp=sp), schema)
    except Exception as e:
        warnings.warn(f'{type(e).__name__} on a constrained call for {schema.__name__} '
                      f'({str(e)[:150]}) — retrying as a JSON reply.')
        return _norm(_json_reply(ch, prompt, schema, sp), schema)

# %% ../nbs/06_extract.ipynb #b6a25c19
EXTRACT_SP = """You pull structured fields out of one document.

Rules:
- Copy what the document states. Do not compute, convert, round or tidy a value.
- A field the document does not state stays empty. An invented number is worse than a blank one.
- Numbers are bare: 1240.50, not "$1,240.50". The currency belongs in its own field.
- Dates are ISO: 2024-03-01.
- A list field takes every entry the document has, in the order it has them."""

@patch
def extract(self:Vault,
            ref:str,               # doc_id, source, title substring, or a path on disk
            schema=None,           # a SCHEMAS key, a dataclass, or a 'field:type, …' spec; None -> from the doctype
            model:str=None,        # an id, a path, `mlx/…`; None -> $VISHALAKSHI_MODEL
            chat_kw:dict=None,     # anything else rishi's `Chat` takes: temp, runtime, think, …
            max_chars:int=8000,    # chars of the document the model sees
            sp:str=EXTRACT_SP,     # system prompt for the extraction
            save:bool=False,       # write the fields into the document's meta
            llm:str='auto',        # the LLM leg of the categorisation, when picking the schema
) -> AttrDict:
    "Pull structured fields out of one document — an invoice's totals, a catalogue's products."
    d = self.document(ref, max_chars=max_chars)
    if not (d.text or '').strip():
        return AttrDict(doc_id=d.doc_id, title=d.title, source=d.source, doctype=None, schema=None,
                        fields={}, skipped='no text to extract from')
    dt, cat = None, None
    if schema is None:
        cat = self.categorize(d, model=model, chat_kw=chat_kw, llm=llm, save=save)
        dt = cat.doctype
        sch = SCHEMAS.get(dt, Summary)
    else: sch = as_schema(schema)
    prompt = (f'{d.title}\n(source: {d.source})\n\n{d.text}\n\n---\n\n'
              f'Pull the fields of `{sch.__name__}` out of the document above.')
    ch = new_chat(model, **(chat_kw or {}))
    flds = structured(ch, prompt, sch, sp=sp)
    if save and d.doc_id: self.set_meta(d.doc_id, extracted=flds, extracted_as=sch.__name__)
    return AttrDict(doc_id=d.doc_id, title=d.title, source=d.source, doctype=dt, schema=sch.__name__,
                    fields=flds, chars=len(d.text), truncated=d.truncated, model=model or dflt_model,
                    runtime=ch.runtime, categorized=cat, usage=getattr(ch, 'use', None))

@patch
def extract_all(self:Vault,
                doctype:str=None,   # only documents already categorised as this
                kind:str=None,      # only these KINDS
                schema=None,        # one shape for all of them; None -> each document's own doctype
                limit:int=None,     # stop after this many
                **kw                # forwarded to extract (model=, chat_kw=, max_chars=, save=, sp=)
) -> AttrDict:
    'Extract from many documents at once — a folder of invoices as one table.'
    docs = self.of_type(doctype, kind) if doctype else self.sources(kind)
    rows, errs = L(), L()
    for r in docs[:limit]:
        try:
            e = self.extract(r['id'], schema=schema, **kw)
            if e.get('skipped'): errs.append(dict(doc_id=r['id'], title=r['title'], error=e.skipped))
            else: rows.append(dict({'doc_id': e.doc_id, 'doc_title': e.title, 'schema': e.schema},
                                   **e.fields))
        except Exception as ex:
            errs.append(dict(doc_id=r['id'], title=r['title'], error=f'{type(ex).__name__}: {str(ex)[:200]}'))
    return AttrDict(n=len(rows), doctype=doctype, schema=schema, rows=rows, errors=errs)

# %% ../nbs/06_extract.ipynb #7c4b0e91
@patch
def ask_doc(self:Vault,
            ref:str,              # doc_id, source, title substring, or a path on disk
            question:str,         # what you want to know about it
            schema=None,          # answer as this shape instead of prose
            max_chars:int=8000,   # chars of the document the model sees
            related:int=3,        # sections from the *rest* of the vault to add as context
            **kw                  # forwarded to `ask` (model=, chat_kw=, sp=)
) -> AttrDict:
    'Answer a question about one whole document — `ask` with that document as section [1].'
    return self.ask(question, ref=ref, schema=schema, doc_chars=max_chars, related=related, **kw)
