"""a durable queue in the vault file: retries with backoff, leases that survive a crash, and a dead letter

Docs: https://vedicreader.github.io/vishalakshi/jobs.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/11_jobs.ipynb.

# %% auto #0
__all__ = ['STATES', 'Retry', 'backoff', 'Queue']

# %% ../nbs/11_jobs.ipynb #2e6f30bb
import json, random, time, uuid
from fastcore.all import AttrDict, L, first, patch, store_attr
from litesearch import write_txn, BUSY_TIMEOUT_MS

STATES = ('ready', 'running', 'done', 'dead')

# %% ../nbs/11_jobs.ipynb #83ac5d12
class Retry(Exception):
    'Raise from a handler to retry work that did not raise on its own: a bot wall, a 429, an empty read.'
    def __init__(self, msg:str='', after:float=None):
        super().__init__(msg)
        self.after = after   # seconds until the retry; None uses the backoff schedule

def backoff(attempt:int,       # failures so far; 1 on the first
            base:float=30,     # first delay, seconds
            cap:float=21600,   # longest delay, 6h
            jitter:float=0.25  # +/- fraction, so jobs that failed together do not retry together
) -> float:
    'Exponential delay before the next attempt.'
    return max(1., min(cap, base * 2**(attempt-1)) * (1 + random.uniform(-jitter, jitter)))

# %% ../nbs/11_jobs.ipynb #bd2c8f19
def _row(r) -> AttrDict:
    'A job row with its payload parsed.'
    d = dict(r)
    p = d.get('payload')
    d['payload'] = json.loads(p) if isinstance(p, str) else (p or {})
    return AttrDict(d)

class Queue:
    "An at-least-once job queue inside an open litesearch database."
    def __init__(self,
                 db,                     # open litesearch/fastlite Database; the queue lives in its file
                 lease:float=600,        # seconds a claim is held before another worker may take the job
                 max_attempts:int=5,     # attempts before a job is dead-lettered
                 base:float=30,          # first retry delay; doubles per attempt
                 keep:float=604800,      # how long finished jobs and run history survive `purge`, 7d
                 busy_ms:int=BUSY_TIMEOUT_MS):  # lock wait before a write gives up; apsw's stock default is 100ms
        store_attr()
        self.handlers = {}
        self._mk()

    def _mk(self):
        'The two tables and their indexes, created on first use.'
        # 8 workers on one file exceed apsw's 100ms default and fail the write instead of waiting
        self.db.conn.set_busy_timeout(self.busy_ms)
        self.t = self.db.t.jobs
        self.t.create(id=str, kind=str, payload=str, key=str, state=str, priority=int, run_at=float,
                      lease_until=float, worker=str, attempt=int, max_attempts=int, error=str,
                      created_at=float, updated_at=float, pk='id', if_not_exists=True)
        self.runs = self.db.t.job_runs
        self.runs.create(id=str, job_id=str, kind=str, worker=str, status=str, error=str,
                         started_at=float, ended_at=float, took=float, pk='id', if_not_exists=True)
        for sql in (
            "CREATE INDEX IF NOT EXISTS jobs_due ON jobs(priority, run_at) WHERE state='ready'",
            "CREATE INDEX IF NOT EXISTS jobs_lease ON jobs(lease_until) WHERE state='running'",
            "CREATE UNIQUE INDEX IF NOT EXISTS jobs_key ON jobs(kind, key) "
            "WHERE key IS NOT NULL AND state IN ('ready','running')",
            "CREATE INDEX IF NOT EXISTS job_runs_job ON job_runs(job_id, started_at)"):
            self.db.conn.execute(sql)

    def __repr__(self):
        s = self.stats()
        return f"Queue({s['ready']} ready, {s['running']} running, {s['done']} done, {s['dead']} dead)"

# %% ../nbs/11_jobs.ipynb #7cc41a60
@patch
def enqueue(self:Queue,
            kind:str,             # which handler runs it
            payload:dict=None,    # arguments, stored as JSON
            run_at:float=None,    # epoch seconds; defaults to now
            priority:int=0,       # lower runs first
            key:str=None,         # idempotency key: an identical key still ready or running wins
            max_attempts:int=None
) -> AttrDict:
    'Add one job, or return the pending one that `key` already names.'
    now = time.time()
    row = dict(id=uuid.uuid4().hex[:12], kind=kind, payload=json.dumps(payload or {}), key=key,
               state='ready', priority=priority, run_at=run_at if run_at is not None else now,
               lease_until=0., worker=None, attempt=0, max_attempts=max_attempts or self.max_attempts,
               error=None, created_at=now, updated_at=now)
    with write_txn(self.db):
        if key is not None and (was := first(self.db.q(
                "SELECT * FROM jobs WHERE kind=? AND key=? AND state IN ('ready','running')", [kind, key]))):
            return _row(was)
        self.t.insert(row)
    return _row(row)

@patch
def enqueue_all(self:Queue, kind:str, payloads, **kw) -> L:
    'Enqueue many jobs of one kind in a single transaction.'
    with write_txn(self.db): return L(payloads).map(lambda p: self.enqueue(kind, p, **kw))

# %% ../nbs/11_jobs.ipynb #cd7f2b48
@patch
def claim(self:Queue,
          worker:str='worker',  # who is holding the lease; recorded on the row and in history
          n:int=1,              # how many jobs to take
          now:float=None
) -> L:
    'Take up to `n` due jobs, atomically. 0 double-claims over 400 jobs and 8 processes, `evals/jobs.py`.'
    now = time.time() if now is None else now
    with write_txn(self.db):
        rows = self.db.q(
            'UPDATE jobs SET state=?, worker=?, lease_until=?, updated_at=? WHERE id IN '
            '(SELECT id FROM jobs WHERE state=? AND run_at<=? ORDER BY priority, run_at LIMIT ?) '
            'RETURNING *', ['running', worker, now + self.lease, now, 'ready', now, n])
    # ORDER BY picks *which* rows; RETURNING hands them back in no defined order, so sort again here
    return L(sorted(rows, key=lambda r: (r['priority'], r['run_at']))).map(_row)

@patch
def _held(self:Queue, job) -> dict|None:
    "The row as it stands, or None if this worker no longer holds it. Call inside a `write_txn`."
    cur = first(self.db.q('SELECT * FROM jobs WHERE id=?', [job['id']]))
    if cur is None or cur['state'] != 'running' or cur['worker'] != job.get('worker'): return None
    return cur

@patch
def ack(self:Queue, job) -> AttrDict:
    "Mark a claimed job finished. A worker whose lease was reclaimed cannot: it comes back `lost`."
    with write_txn(self.db):
        if self._held(job) is None: return _row(dict(job, state='lost'))
        self.db.q('UPDATE jobs SET state=?, error=NULL, worker=NULL, lease_until=0, updated_at=? WHERE id=?',
                  ['done', time.time(), job['id']])
    return _row(dict(job, state='done'))

@patch
def fail(self:Queue,
         job,                # the claimed job
         error:str,          # what went wrong; truncated to 500 chars on the row
         after:float=None    # seconds until the retry; None uses `backoff`
) -> AttrDict:
    'Back off and retry, or dead-letter once the attempts are spent.'
    now, err = time.time(), str(error)[:500]
    with write_txn(self.db):
        if (cur := self._held(job)) is None: return _row(dict(job, state='lost'))
        att = cur['attempt'] + 1
        dead = att >= (cur['max_attempts'] or self.max_attempts)
        nxt = cur['run_at'] if dead else now + (backoff(att, base=self.base) if after is None else after)
        self.db.q('UPDATE jobs SET state=?, attempt=?, run_at=?, error=?, worker=NULL, lease_until=0, '
                  'updated_at=? WHERE id=?', ['dead' if dead else 'ready', att, nxt, err, now, cur['id']])
    return _row(dict(cur, state='dead' if dead else 'ready', attempt=att, run_at=nxt, error=err))

@patch
def reclaim(self:Queue, now:float=None) -> L:
    'Return jobs whose lease expired to the queue: a worker killed mid-job loses its claim, not its job.'
    now = time.time() if now is None else now
    exp = self.db.q('SELECT * FROM jobs WHERE state=? AND lease_until>0 AND lease_until<=?', ['running', now])
    # two pollers can read the same expired row; the fence in `fail` means only one of them counts it
    return L(exp).map(lambda j: self.fail(j, 'lease expired')).filter(lambda j: j['state'] != 'lost')

# %% ../nbs/11_jobs.ipynb #06be5c39
@patch
def on(self:Queue, kind:str):
    'Decorator registering the handler for `kind`.'
    def _f(fn):
        self.handlers[kind] = fn
        return fn
    return _f

@patch
def register(self:Queue, kind:str, fn):
    'Register the handler for `kind`.'
    self.handlers[kind] = fn
    return fn

@patch
def _ran(self:Queue, job, status:str, t0:float, error:str=None, result=None) -> AttrDict:
    'Write one row of run history and return what the caller reports.'
    now = time.time()
    self.runs.insert(dict(id=uuid.uuid4().hex[:12], job_id=job['id'], kind=job['kind'],
                          worker=job.get('worker'), status=status, error=(error or None),
                          started_at=t0, ended_at=now, took=round(now-t0, 3)))
    return AttrDict(job_id=job['id'], kind=job['kind'], status=status, took=round(now-t0, 3),
                    error=error, result=result)

@patch
def run_one(self:Queue, job) -> AttrDict:
    'Dispatch one claimed job, then ack or fail it, and record the run either way.'
    t0 = time.time()
    # ack and fail are fenced, so a call that lost its lease changed nothing and the run says `lost`
    def _rep(out, status, error=None, result=None):
        if out['state'] == 'lost': status, error = 'lost', 'the lease was reclaimed mid-handler'
        return self._ran(job, status, t0, error, result)
    if (fn := self.handlers.get(job['kind'])) is None:
        err = f"no handler for {job['kind']!r}"
        return _rep(self.fail(job, err), 'error', err)
    try: res = fn(job['payload'])
    except Retry as e: return _rep(self.fail(job, f'Retry: {e}', after=e.after), 'retry', str(e))
    except Exception as e:
        err = f'{type(e).__name__}: {str(e)[:200]}'
        return _rep(self.fail(job, err), 'error', err)
    return _rep(self.ack(job), 'skipped' if isinstance(res, dict) and res.get('skipped') else 'ok',
                None, res)

@patch
def drain(self:Queue,
          worker:str='worker',  # lease holder recorded on each job
          limit:int=1000,       # jobs to run before returning; a ceiling, not a target
          batch:int=1,          # jobs claimed per round trip
          now:float=None
) -> L:
    'Claim and run until the queue is empty or `limit` jobs have run. This is the tick a cron calls.'
    out = L()
    while len(out) < limit:
        got = self.claim(worker, n=min(batch, limit-len(out)), now=now)
        if not got: break
        out += got.map(self.run_one)
    return out

# %% ../nbs/11_jobs.ipynb #5a1e7d92
@patch
def jobs(self:Queue, state:str=None, kind:str=None, limit:int=100) -> L:
    'Jobs, soonest first, filtered by state and kind.'
    w, a = [], []
    if state: w.append('state=?'); a.append(state)
    if kind:  w.append('kind=?');  a.append(kind)
    sql = 'SELECT * FROM jobs' + (' WHERE ' + ' AND '.join(w) if w else '') + ' ORDER BY run_at LIMIT ?'
    return L(self.db.q(sql, a + [limit])).map(_row)

@patch
def dead(self:Queue, limit:int=100) -> L:
    'Jobs that used up their attempts, with the error that finished them off.'
    return self.jobs(state='dead', limit=limit)

@patch
def pending(self:Queue, kind:str=None) -> int:
    'How many jobs are ready or running: what is left to do, counted rather than listed.'
    w, a = ('AND kind=? ', [kind]) if kind else ('', [])
    return first(self.db.q(f"SELECT count(*) n FROM jobs WHERE state IN ('ready','running') {w}", a))['n']

@patch
def retry(self:Queue, job_id:str, after:float=0) -> AttrDict:
    'Put a dead or pending job back on the queue now, with its attempt count reset.'
    now = time.time()
    self.db.q('UPDATE jobs SET state=?, attempt=0, run_at=?, error=NULL, worker=NULL, lease_until=0, '
              'updated_at=? WHERE id=?', ['ready', now+after, now, job_id])
    return first(L(self.db.q('SELECT * FROM jobs WHERE id=?', [job_id])).map(_row))

@patch
def history(self:Queue, job_id:str=None, limit:int=50) -> L:
    'Run history, newest first.'
    w, a = ('WHERE job_id=? ', [job_id]) if job_id else ('', [])
    return L(self.db.q(f'SELECT * FROM job_runs {w}ORDER BY started_at DESC LIMIT ?', a + [limit]))

@patch
def stats(self:Queue) -> dict:
    'How many jobs in each state, and when the next one is due.'
    by = {r['state']: r['n'] for r in self.db.q('SELECT state, count(*) n FROM jobs GROUP BY state')}
    nxt = first(self.db.q("SELECT min(run_at) t FROM jobs WHERE state='ready'"))
    return dict({s: by.get(s, 0) for s in STATES}, next_due=nxt['t'])

@patch
def purge(self:Queue, before:float=None) -> dict:
    'Delete finished jobs and run history older than `keep`. Dead jobs stay.'
    cut = (time.time() - self.keep) if before is None else before
    d = self.db.q("DELETE FROM jobs WHERE state='done' AND updated_at<? RETURNING id", [cut])
    r = self.db.q('DELETE FROM job_runs WHERE ended_at<? RETURNING id', [cut])
    return dict(jobs=len(d), runs=len(r))
