"""the vault as MCP tools any client can drive

Docs: https://vedicreader.github.io/vishalakshi/mcp.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_mcp.ipynb.

# %% auto #0
__all__ = ['TOOLS', 'mcp', 'as_tool', 'main']

# %% ../nbs/05_mcp.ipynb #154261c1
import json, sys
from functools import wraps
from .cli import cmd, jsonable, vault

# mcp 2.0 renamed FastMCP to MCPServer and moved it; the constructor, the `tool` decorator and the
# `run` transports are unchanged, so one alias covers both SDKs rather than pinning either.
try: from mcp.server.mcpserver import MCPServer
except ImportError:
    try: from mcp.server.fastmcp import FastMCP as MCPServer
    except ImportError as e:
        raise ImportError('vishalakshi-mcp needs the `mcp` package — `pip install mcp`') from e

# %% ../nbs/05_mcp.ipynb #fad2b047
TOOLS = ('stats find sections context ask read related toc map sources document shelves elsewhere grab url '
         'web arxiv youtube add_file add_dir add_tree note connect forget apis harvest watch watches '
         'poll unwatch index_code code_search symbol where_to_add grep federate categorize '
         'categorize_all doctypes of_type ner reshelf extract extract_all ask_doc').split()

mcp = MCPServer('vishalakshi', instructions=(
    'A personal research vault: web pages, papers, transcripts, files, code and notes in one '
    'searchable corpus. `context` is the main tool — it returns whole sections plus what they '
    'connect to, which is what you want before answering a question. `find` locates things, '
    '`read` pulls one section in full, `related` answers "what else reads like this". `grab` '
    'files anything you point it at; `note` writes your own conclusions back so they are searched '
    'alongside the sources. `add_tree` points at a directory and splits it: documents into the '
    'vault, source files into kosha, entity graph rebuilt once at the end. When kosha has indexed '
    'the repo, `context` and `ask` add code sections to what they retrieve on their own, so a '
    'question about the user\'s own system is answered from the source rather than from prose about '
    'it.\n\n'
    'For one document rather than the corpus: `document` returns the whole of it, `categorize` says '
    'what kind of thing it is (invoice, catalogue, contract, paper, …), `extract` pulls its fields '
    'out against a schema — a name like `invoice`, or a spec like `vendor:str, total:float` you '
    'make up on the spot — and `ask_doc` answers a question about that document with the rest of '
    'the vault as context, as prose or as a shape you name. `extract_all` does it across every '
    'document of one type, which is how a folder of invoices becomes a table.'))

def as_tool(name:str):
    'Register one `Vault` method as an MCP tool, forcing its result through JSON.'
    f = cmd(name)
    g = wraps(f)(lambda **kw: json.loads(json.dumps(f(**kw), default=jsonable)))
    g.__signature__, g.__delwrap__, g.__annotations__ = f.__signature__, f.__delwrap__, f.__annotations__
    return mcp.tool(name=name)(g)

for _t in TOOLS: as_tool(_t)

def main():
    'Entry point for `vishalakshi-mcp`. stdio by default; `--http` for Streamable HTTP.'
    mcp.run(transport='streamable-http' if '--http' in sys.argv[1:] else 'stdio')
