"""whether a document is somebody's business, decided by arithmetic rather than by a model

Docs: https://vedicreader.github.io/vishalakshi/pii.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/09_pii.ipynb.

# %% auto #0
__all__ = ['MAX_SCAN', 'DENSE', 'PATTERNS', 'IDENTIFYING', 'luhn', 'person_spans', 'pii_spans', 'pii_report', 'redact',
           'redact_obj', 'pii_ctx']

# %% ../nbs/09_pii.ipynb #d2947634
import re
from fastcore.all import AttrDict, L

# %% ../nbs/09_pii.ipynb #f6e67e8b
MAX_SCAN, DENSE = 200_000, 1.0

# %% ../nbs/09_pii.ipynb #372845f0
def luhn(s:str) -> bool:
    "The check digit every payment card carries. Sixteen digits that fail it are not a card."
    ds = [int(c) for c in s if c.isdigit()]
    if len(ds) < 12: return False
    tot, parity = 0, len(ds) % 2
    for i, d in enumerate(ds):
        if i % 2 == parity: d *= 2; d -= 9 if d > 9 else 0
        tot += d
    return tot % 10 == 0

def _iban_ok(s:str) -> bool:
    "IBAN's mod-97 check: move the country prefix to the end, letters to digits, remainder must be 1."
    s = re.sub(r'[^A-Za-z0-9]', '', s).upper()
    if not (15 <= len(s) <= 34): return False
    t = s[4:] + s[:4]
    try: n = int(''.join(str(int(c, 36)) for c in t))
    except ValueError: return False
    return n % 97 == 1

def _nhs_ok(s:str) -> bool:
    "The UK NHS number's mod-11 check digit. Ten digits in a row are otherwise just ten digits."
    ds = [int(c) for c in s if c.isdigit()]
    if len(ds) != 10: return False
    tot = sum(d * (10 - i) for i, d in enumerate(ds[:9]))
    chk = 11 - tot % 11
    return chk != 10 and (0 if chk == 11 else chk) == ds[9]

def _ssn_ok(s:str) -> bool:
    "A US SSN's structurally impossible cases, which is as much as arithmetic can say about one."
    ds = re.sub(r'\D', '', s)
    if len(ds) != 9: return False
    a, b, c = ds[:3], ds[3:5], ds[5:]
    return a not in ('000', '666') and a[0] != '9' and b != '00' and c != '0000'

# %% ../nbs/09_pii.ipynb #42e59a18
#: kind -> (pattern, validator or None). Spans de-overlapped longest-first.
PATTERNS = {
    'email':   (r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b', None),
    'card':    (r'\b(?:\d[ -]?){13,19}\b', luhn),
    'iban':    (r'\b[A-Z]{2}\d{2}[ ]?(?:[A-Z0-9]{4}[ ]?){2,7}[A-Z0-9]{1,4}\b', _iban_ok),
    'ssn':     (r'\b\d{3}-\d{2}-\d{4}\b', _ssn_ok),
    'nhs':     (r'\b\d{3}[ -]?\d{3}[ -]?\d{4}\b', _nhs_ok),
    'phone':   (r'\+\d{1,3}[ .-]?\(?\d{1,5}\)?[ .-]?\d{3,4}[ .-]?\d{3,4}\b'
                r'|\(\d{2,5}\)[ .-]?\d{3,4}[ .-]?\d{3,4}\b'
                r'|\b0\d{1,4}[ .-]\d{3,4}[ .-]?\d{3,4}\b'
                r'|\b\d{3}-\d{3}-\d{4}\b'
                r'|\b(?:phone|tel|telephone|mobile|cell|fax)\b\W{0,8}\+?[\d ().-]{7,20}\d', None),
    'ip':      (r'\b(?:(?:25[0-5]|2[0-4]\d|1?\d?\d)\.){3}(?:25[0-5]|2[0-4]\d|1?\d?\d)\b', None),
    'dob':     (r'\b(?:date of birth|dob|born)\b\W{0,12}(?:\d{1,4}[/-]\d{1,2}[/-]\d{1,4}|\d{1,2} \w+ \d{4})', None),
    'passport':(r'\b(?:passport(?:\s*(?:no|number|#))?)\W{0,6}[A-Z0-9]{6,9}\b', None),
    'licence': (r'\b(?:driver.?s? licen[cs]e|dl)(?:\s*(?:no|number|#))?\W{0,6}[A-Z0-9]{5,20}\b', None),
    'account': (r'\b(?:account|acct|a/c)(?:\s*(?:no|number|#))?\W{0,6}\d{6,17}\b', None),
    'sortcode':(r'\b(?:sort\s*code)\W{0,6}\d{2}[- ]?\d{2}[- ]?\d{2}\b', None),
    'secret':  (r'\b(?:sk-[A-Za-z0-9_-]{16,}|ghp_[A-Za-z0-9]{20,}|xox[baprs]-[A-Za-z0-9-]{10,}|AKIA[0-9A-Z]{16}|AIza[0-9A-Za-z_-]{35})\b', None),
    'medical': (r'\b(?:patient (?:id|number|name)|nhs number|medical record(?:\s*(?:no|number|#))?|mrn\W{0,6}\w+)\b', None),
    # require a street name between number and suffix (0.948 vs 0.746 without, evals/pii.py)
    'address': (r'\b\d{1,5}[A-Za-z]?[ ,]+(?:[A-Z][A-Za-z.\'-]+[ ,]+){1,3}'
                r'(?:Street|St|Road|Rd|Avenue|Ave|Lane|Ln|Drive|Boulevard|Blvd|Close|Court|Ct'
                r'|Crescent|Way|Place|Terrace|Square|Sq|Gardens|Grove|Row|Walk)\b\.?'
                r'|\b[A-Z]{1,2}\d[A-Z\d]? ?\d[A-Z]{2}\b'
                r'|\b[A-Z]{2} \d{5}(?:-\d{4})?\b', None),
}
#: `person` is the one kind arithmetic cannot find, and the only one gated behind `ner=True`.
IDENTIFYING = frozenset({'email', 'card', 'iban', 'ssn', 'nhs', 'phone', 'dob', 'passport', 'licence', 'account',
                         'sortcode', 'medical', 'secret', 'address', 'person'})
_COMPILED = {k: (re.compile(p, re.I), v) for k, (p, v) in PATTERNS.items()}


# %% ../nbs/09_pii.ipynb #d1ff54dc
def _scan_parts(text:str, mx:int=MAX_SCAN) -> list:
    """Both ends of a long document as `(offset, part)` (headers/footers hold identifiers)."""
    text = str(text or '')
    if len(text) <= mx: return [(0, text)]
    half = mx // 2
    return [(0, text[:half]), (half + 1, text[-half:])]

def _scan_text(text:str, mx:int=MAX_SCAN) -> str:
    "The part of a long document worth scanning, joined for measurement. Offsets follow `_scan_parts`."
    return '\n'.join(p for _, p in _scan_parts(text, mx))

def person_spans(text:str,     # what to scan
                 mx:int=None,  # chars handed to the extractor; None -> `extract.NER_CHARS`
) -> L:
    """Honorific-anchored personal names. Off by default; costs an entity pass."""
    from vishalakshi.extract import NER_CHARS, _noun_ents
    text = str(text or '')[:mx or NER_CHARS]
    out = []
    for surface, label in _noun_ents(text):
        if label != 'PERSON': continue
        out += [(m.start(), m.end(), 'person', surface) for m in re.finditer(re.escape(surface), text)]
    return L(out)

def pii_spans(text:str,          # what to scan
              kinds=None,        # restrict to these kinds; None -> every pattern
              mx:int=MAX_SCAN,   # chars scanned before a long document is sampled at both ends
              ner:bool=False,    # also look for names, which no pattern can find
) -> L:
    """Every match, as `(start, end, kind, text)`, longest first and never overlapping."""
    want = set(kinds or (*_COMPILED, 'person'))
    found = []
    for off, part in _scan_parts(text, mx):
        for kind, (rx, ok) in _COMPILED.items():
            if kind not in want: continue
            for m in rx.finditer(part):
                if ok is not None and not ok(m.group(0)): continue
                found.append((off + m.start(), off + m.end(), kind, m.group(0)))
        if ner and 'person' in want:
            found += [(off + s, off + e, k, v) for s, e, k, v in person_spans(part)]
    found.sort(key=lambda s: (s[0] - s[1], s[0]))       # longest first, then leftmost
    out, taken = [], []
    for s, e, kind, val in found:
        if any(s < te and ts < e for ts, te in taken): continue
        taken.append((s, e))
        out.append((s, e, kind, val))
    return L(sorted(out))


# %% ../nbs/09_pii.ipynb #1f8b0234
def pii_report(text:str,          # what to scan
               kinds=None,        # restrict to these kinds; None -> every pattern
               mx:int=MAX_SCAN,   # chars scanned before a long document is sampled at both ends
               ner:bool=False,    # also look for names
) -> AttrDict:
    """Spans found and whether they tip `has_pii` (IDENTIFYING kinds only)."""
    spans, counts = pii_spans(text, kinds, mx, ner=ner), {}
    for _, _, k, _ in spans: counts[k] = counts.get(k, 0) + 1
    n = len(_scan_text(text, mx))
    ident = {k: v for k, v in counts.items() if k in IDENTIFYING}
    # `n` and `density` stay arithmetic-only, or `DENSE` would mean something new the day NER came on
    n_arith = len(spans) - counts.get('person', 0)
    return AttrDict(has_pii=bool(ident), kinds=counts, identifying=ident, n=n_arith,
                    n_person=counts.get('person', 0), scanned=n, scanned_ner=bool(ner),
                    density=round(1000 * n_arith / max(n, 1), 3), spans=spans)


# %% ../nbs/09_pii.ipynb #bb39f244
def redact(text:str,       # the text to mask
           spans=None,     # spans from `pii_spans`; recomputed over the whole of `text` when None
           kinds=None,     # restrict to these kinds
           mask:str=None,  # what to put in place of a match; None -> `[KIND]`
           ner:bool=False, # also mask names
) -> str:
    """Mask matched spans. Names only with `ner=True`."""
    out = str(text or '')
    if spans is None: spans = pii_spans(out, kinds, mx=len(out), ner=ner)
    for s, e, kind, _ in sorted(spans, reverse=True):
        out = out[:s] + (mask if mask is not None else f'[{kind.upper()}]') + out[e:]
    return out


# %% ../nbs/09_pii.ipynb #e7e2b7b9
from .core import Vault
from fastcore.all import patch

def redact_obj(o, kinds=None, ner:bool=False):
    "`redact` over the strings inside a nested dict or list: what a structured answer is."
    if isinstance(o, str):  return redact(o, kinds=kinds, ner=ner)
    if isinstance(o, dict): return {k: redact_obj(v, kinds, ner) for k, v in o.items()}
    if isinstance(o, list): return [redact_obj(v, kinds, ner) for v in o]
    return o

@patch
def pii(self:Vault,
        ref,                 # a doc_id, source, title or path: whatever `document` takes
        max_chars:int=MAX_SCAN,
        ner:bool=False,      # also look for names, except on code, where identifiers are not names
) -> AttrDict:
    "Whether one whole document is somebody's business, and what in it says so."
    d = self.document(ref, max_chars=max_chars)
    # `scanned_ner` then reports False, which is the honest answer: nothing looked for a name here
    r = pii_report(d.text, ner=ner and (d.get('kind') or '') != 'code')
    override = (self.marks(d.get('doc_id')) or {}).get('pii_override') if d.get('doc_id') else None
    r.detected, r.override = r.has_pii, override
    if override == 'clear': r.has_pii = False
    elif override == 'force': r.has_pii = True
    r.doc_id, r.title, r.source = d.get('doc_id'), d.get('title'), d.get('source')
    return r

@patch
def mark_not_pii(self:Vault, ref, clear:bool=True, reason:str='') -> dict:
    "Clear a false-positive PII decision (`pii_override='clear'`), or restore automatic detection."
    return self.mark(ref, pii_override='clear' if clear else None,
                     pii_reason=(reason or None) if clear else None)

@patch
def mark_pii(self:Vault, ref, force:bool=True, reason:str='') -> dict:
    "Force a document private even when arithmetic finds nothing (names, addresses, whole PDFs)."
    return self.mark(ref, pii_override='force' if force else None,
                     pii_reason=(reason or None) if force else None)

def pii_ctx(ctx, ner:bool=False) -> AttrDict:
    "The report for an assembled context, which is what a policy has to gate on."
    parts = [str(getattr(r, 'text', None) or (r.get('text') if isinstance(r, dict) else '') or '')
             for r in (list(ctx.get('results') or []) + list(ctx.get('related') or []))]
    return pii_report('\n\n'.join(parts), ner=ner)
