"""one vault for everything you have read: web pages, papers, video, files, code and your own notes in one SQLite
file, searchable together and answerable by a local or hosted model

## Getting started

```python
from vishalakshi.skill import vault
v = vault()                      # $VISHALAKSHI_VAULT, else ~/.vishalakshi/vault.db
```

One vault holds everything. `add` takes a directory, a file, or text; `grab` takes anything at all
and routes on what it is (an arXiv id, a YouTube link, a GitHub repo, a PDF url, a path).

```python
v.add('~/notes')                 # a directory, a file, or a string of text
v.grab('1706.03762')             # arXiv id, YouTube url, GitHub repo, PDF url, path
v.note('what I concluded', tags=['retrieval'])
```

## Reading it back

Four calls, in the order you usually want them.

```python
v.context(q)                     # start here: whole sections plus what they connect to
v.ask(q)                         # an answer with [n] citations that resolve to node_ids
v.search(q, limit=10)            # chunk hits, each with a breadcrumb and a node_id
v.sections(q, limit=5)           # ranked sections rather than chunks
v.read(node_id)                  # the section behind a citation, in full
```

`context` is the one to hand a model. `search` is for locating a fact you can already name.
`sections` is for a topic. Every hit carries a `node_id`, and `read(node_id)` opens exactly the text
it came from, which is how a claim gets checked rather than trusted.

`kind` filters any of them without a second pass over the results: `v.search(q, kind='pdf')`, or
`'note,web'` for more than one. The kinds are `web`, `pdf`, `arxiv`, `youtube`, `file`, `code`,
`data`, `note`, plus whatever the file parser called it.

## Answering about documents you name

```python
v.ask_doc(['a.py', 'b.py'], 'what does a do that b does not?')
v.ask_doc(path, 'what is owed and by when?', schema='amount:float, due:str')
```

Neither document need be in the vault; a path on disk is read straight off it. `doc_chars` is the
budget shared between the named documents, so two files at the default 8000 get 4000 characters
each. Raise it when the question is a real comparison, and use a model with the window to match.

## Paperwork, as fields

```python
v.categorize(ref, llm='never')   # invoice? paper? contract? a cue table, no model
v.extract(ref)                   # the doctype picks the schema
v.extract(ref, schema='vendor:str, total:float, due_date:str')
v.extract_all(doctype='invoice') # one row per invoice in the vault
```

`categorize` answers from a regex and entity cue table first and reaches for a model only where the
table cannot decide. `decisive=True` means it did not need one.

## Code

```python
v.index_code(dir)                # fills kosha: AST chunks, symbols, a call graph
v.code_search(q); v.symbol(name); v.where_to_add(desc); v.grep(pat, dir)
v.federate(q, dir=dir)           # vault + kosha + ripgrep, fused by rank
```

Once a repo is indexed, `context` appends code sections on its own, decided by looking for
`.kosha/code.db` on disk rather than by loading anything.

## What is decided, and what is yours

The retrieval defaults are litesearch's measured ones and there is nothing to choose: 512-character
chunks, a preprocessed keyword leg, an HNSW vector leg, a document tree, one static 256d encoder,
and a script fold that makes Devanagari and IAST reach the same row.

Four things are yours. `rerank=True` on `search`, `sections` or `context` is worth +0.026 to +0.077
weighted MRR at roughly 10x the latency. `v.shelf(name)` partitions a corpus so two bodies of
material stop diluting each other. `llm=` decides how hard `categorize` and `extract` try. And
`db.graph_search` is the entity-graph leg, by name, for queries whose answer shares no word with the
question; it is off everywhere else because it costs 0.070 to 0.160 weighted MRR on ordinary ones.

`v.connect()` builds that graph, and `v.map()` reads the topics out of it. Neither is a ranking leg.
They answer the question you ask before you know what to search for: what is in here, and what
connects to what. Run `connect()` after a batch of ingests rather than inside each one.

## Notes

`v.stats()` says what is in the vault, `v.sources()` why each document is there, `v.toc()` its shape.
Ingestion is content-addressed, so re-adding the same source is a no-op rather than a duplicate.
Ingesting Sanskrit switches on vidyut lemmas and Monier-Williams glosses by itself, once.

`forget`, `drop_shelf`, `unwatch` and `pause` delete things and are deliberately not registered with
`allow`, so sandboxed code cannot reach them. Call them yourself when you mean to.

Docs: https://vedicreader.github.io/vishalakshi/skill.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_skill.ipynb.

# %% auto #0
__all__ = ['READ', 'WRITE']

# %% ../nbs/08_skill.ipynb #sk-code
import os
from pyskills import allow
from .core import Vault
from .cli import vault

# Everything a sandboxed agent may call: read the vault, and add to it. The four that delete
# (`forget`, `drop_shelf`, `unwatch`, `pause`) are left out on purpose — an agent filling a vault it
# shares with you should not be able to empty it.
READ = ('search sections context related read toc doc document sources stats shelves elsewhere map '
        'doctypes of_type ner categorize extract extract_all ask ask_doc explain doc_context '
        'code_search symbol where_to_add grep federate watches apis assets').split()
WRITE = ('add add_file add_files add_dir add_tree add_records add_code note grab url web crawl arxiv '
         'pdf youtube github gh_file code connect index_code harvest watch poll run_watch '
         'categorize_all set_meta reshelf shelf route').split()

allow(vault, {Vault: READ + WRITE})
